In [ ]:
import pandas as pd
import yfinance as yf
import numpy as np

In [ ]:
portfolio = ['RELIANCE.NS','TCS.NS','INFY.NS','HDFCBANK.NS','ICICIBANK.NS']

In [ ]:
start_date = '2023-01-01'
end_date = '2026-01-01'

In [ ]:
for stock in portfolio:
  yf.download(stock, start=start_date, end= end_date)

/tmp/ipykernel_1582/3973490860.py:2: FutureWarning: YF.download() has changed argument auto_adjust default to True
  yf.download(stock, start=start_date, end= end_date)
[*********************100%***********************]  1 of 1 completed
/tmp/ipykernel_1582/3973490860.py:2: FutureWarning: YF.download() has changed argument auto_adjust default to True
  yf.download(stock, start=start_date, end= end_date)
[*********************100%***********************]  1 of 1 completed
/tmp/ipykernel_1582/3973490860.py:2: FutureWarning: YF.download() has changed argument auto_adjust default to True
  yf.download(stock, start=start_date, end= end_date)
[*********************100%***********************]  1 of 1 completed
/tmp/ipykernel_1582/3973490860.py:2: FutureWarning: YF.download() has changed argument auto_adjust default to True
  yf.download(stock, start=start_date, end= end_date)
[*********************100%***********************]  1 of 1 completed
/tmp/ipykernel_1582/3973490860.py:2: FutureWarning: YF.download() has changed argument auto_adjust default to True
  yf.download(stock, start=start_date, end= end_date)
[*********************100%***********************]  1 of 1 completed

In [ ]:
print(portfolio)

['RELIANCE.NS', 'TCS.NS', 'INFY.NS', 'HDFCBANK.NS', 'ICICIBANK.NS']

In [ ]:
raw_data = {}

for stock in portfolio:
  raw_data[stock] = yf.download(stock, start=start_date, end= end_date)

/tmp/ipykernel_1582/2133735910.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  raw_data[stock] = yf.download(stock, start=start_date, end= end_date)
[*********************100%***********************]  1 of 1 completed
/tmp/ipykernel_1582/2133735910.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  raw_data[stock] = yf.download(stock, start=start_date, end= end_date)
[*********************100%***********************]  1 of 1 completed
/tmp/ipykernel_1582/2133735910.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  raw_data[stock] = yf.download(stock, start=start_date, end= end_date)
[*********************100%***********************]  1 of 1 completed
/tmp/ipykernel_1582/2133735910.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  raw_data[stock] = yf.download(stock, start=start_date, end= end_date)
[*********************100%***********************]  1 of 1 completed
/tmp/ipykernel_1582/2133735910.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  raw_data[stock] = yf.download(stock, start=start_date, end= end_date)
[*********************100%***********************]  1 of 1 completed

In [ ]:
raw_data.keys()

dict_keys(['RELIANCE.NS', 'TCS.NS', 'INFY.NS', 'HDFCBANK.NS', 'ICICIBANK.NS'])

In [ ]:
raw_data.values()

dict_values([Price             Close         High          Low         Open      Volume
Ticker      RELIANCE.NS  RELIANCE.NS  RELIANCE.NS  RELIANCE.NS RELIANCE.NS
Date
2023-01-02  1170.477783  1171.886424  1157.891000  1158.708901     5316175
2023-01-03  1161.912354  1169.160003  1157.709267  1165.547536     7658932
2023-01-04  1144.418213  1163.730055  1142.350684  1161.889687     9264891
2023-01-05  1142.373535  1152.529332  1137.806870  1146.667607    13637099
2023-01-06  1152.756348  1157.777455  1144.304622  1148.098818     6349597
...                 ...          ...          ...          ...         ...
2025-12-24  1551.028687  1568.448147  1546.449881  1565.461954     8815745
2025-12-26  1552.024048  1553.815812  1547.146696  1547.544758     2311495
2025-12-29  1538.486694  1550.929166  1536.495899  1547.743942     5972105
2025-12-30  1532.713379  1546.449794  1530.722584  1539.880194     8815884
2025-12-31  1563.172607  1569.742208  1533.907890  1533.907890     5771830

[740 rows x 5 columns], Price             Close         High          Low         Open   Volume
Ticker           TCS.NS       TCS.NS       TCS.NS       TCS.NS   TCS.NS
Date
2023-01-02  2877.781250  2882.546137  2854.619233  2877.384230   709547
2023-01-03  2921.811279  2929.443629  2863.531191  2869.442976  1245178
2023-01-04  2924.722412  2935.928587  2899.619245  2917.707674  1231668
2023-01-05  2921.590820  2944.708677  2895.869822  2938.443816  1826057
2023-01-06  2833.751221  2913.163843  2823.559891  2911.796138  2488376
...                 ...          ...          ...          ...      ...
2025-12-24  3198.595947  3206.402196  3176.526789  3184.236572  1367708
2025-12-26  3161.010986  3199.559901  3153.108506  3192.910307  1176664
2025-12-29  3133.544434  3168.720313  3125.256324  3161.010531  2079473
2025-12-30  3129.015381  3148.964397  3121.980157  3132.099247  2807593
2025-12-31  3089.888184  3128.244400  3082.467565  3122.462063  3362634

[740 rows x 5 columns], Price             Close         High          Low         Open   Volume
Ticker          INFY.NS      INFY.NS      INFY.NS      INFY.NS  INFY.NS
Date
2023-01-02  1368.097534  1370.341789  1350.188427  1359.120516  3801140
2023-01-03  1366.795776  1375.862542  1360.107833  1364.371916  4551130
2023-01-04  1341.884521  1365.404262  1338.562960  1365.404262  7059590
2023-01-05  1324.289551  1351.849060  1318.948269  1351.849060  9868404
2023-01-06  1300.320923  1324.110018  1298.525519  1319.621510  6443714
...                 ...          ...          ...          ...      ...
2025-12-24  1628.167480  1632.278472  1617.498330  1625.818291  4271167
2025-12-26  1621.022095  1633.453168  1616.715267  1628.167521  2006491
2025-12-29  1609.863525  1637.662008  1602.424525  1622.881866  4062817
2025-12-30  1587.252808  1612.995794  1582.554548  1612.114833  9395937
2025-12-31  1581.184204  1594.104567  1575.115455  1586.665566  6538656

[740 rows x 5 columns], Price            Close        High         Low        Open      Volume
Ticker     HDFCBANK.NS HDFCBANK.NS HDFCBANK.NS HDFCBANK.NS HDFCBANK.NS
Date
2023-01-02  770.927124  776.157543  766.122780  770.122471     4381378
2023-01-03  775.968262  777.695961  767.850486  767.850486     8378030
2023-01-04  762.099426  778.997604  760.655719  773.909210    10351600
2023-01-05  757.200378  765.886195  752.325021  764.442488    10941436
2023-01-06  754.691711  761.649772  747.023585  758.289076     9092462
...                ...         ...         ...         ...         ...
2025-12-24  980.975220  983.139437  976.843543  976.843543    13699996
2025-12-26  975.958191  980.975248  971.629816  979.794761     9360853
2025-12-29  975.564697  981.171968  971.137914  976.941883    13545749
2025-12-30  974.777771  978.811039  966.219311  974.089148    33155849
2025-12-31  975.072876  981.368710  971.531413  974.876118    10963454

[740 rows x 5 columns], Price             Close         High          Low         Open       Volume
Ticker     ICICIBANK.NS ICICIBANK.NS ICICIBANK.NS ICICIBANK.NS ICICIBANK.NS
Date
2023-01-02   873.285095   877.688039   865.108166   865.108166      4315403
2023-01-03   872.220642   876.672017   867.769326   869.462770      5846855
2023-01-04   870.043335   878.558988   865.882312   869.946590     12454582
2023-01-05   850.738159   873.817365   843.819205   871.785255     16547196
2023-01-06   841.980530   850.544555   832.690801   850.544555     14804613
...                 ...          ...          ...          ...          ...
2025-12-24  1348.432129  1356.761808  1346.250448  1352.398689      8955140
2025-12-26  1339.110596  1350.613595  1337.226456  1345.159575      2812144
2025-12-29  1332.070068  1344.366308  1330.285068  1340.796428      6057201
2025-12-30  1331.276611  1335.838131  1326.913371  1332.069972     18621277
2025-12-31  1331.673340  1338.713959  1328.301740  1331.574200      6150634

[740 rows x 5 columns]])

In [ ]:
def standardize_data(df,ticker):
  df = df.reset_index()
  df.columns = [col[0] for col in df.columns]
  df["ticker"] = ticker
  return df

In [ ]:
processed_data = {}
for stock in portfolio:
  processed_data[stock] = standardize_data(raw_data[stock], stock)

In [ ]:
processed_data.values()

dict_values([          Date        Close         High          Low         Open    Volume  \
0   2023-01-02  1170.477783  1171.886424  1157.891000  1158.708901   5316175
1   2023-01-03  1161.912354  1169.160003  1157.709267  1165.547536   7658932
2   2023-01-04  1144.418213  1163.730055  1142.350684  1161.889687   9264891
3   2023-01-05  1142.373535  1152.529332  1137.806870  1146.667607  13637099
4   2023-01-06  1152.756348  1157.777455  1144.304622  1148.098818   6349597
..         ...          ...          ...          ...          ...       ...
735 2025-12-24  1551.028687  1568.448147  1546.449881  1565.461954   8815745
736 2025-12-26  1552.024048  1553.815812  1547.146696  1547.544758   2311495
737 2025-12-29  1538.486694  1550.929166  1536.495899  1547.743942   5972105
738 2025-12-30  1532.713379  1546.449794  1530.722584  1539.880194   8815884
739 2025-12-31  1563.172607  1569.742208  1533.907890  1533.907890   5771830

          ticker
0    RELIANCE.NS
1    RELIANCE.NS
2    RELIANCE.NS
3    RELIANCE.NS
4    RELIANCE.NS
..           ...
735  RELIANCE.NS
736  RELIANCE.NS
737  RELIANCE.NS
738  RELIANCE.NS
739  RELIANCE.NS

[740 rows x 7 columns],           Date        Close         High          Low         Open   Volume  \
0   2023-01-02  2877.781250  2882.546137  2854.619233  2877.384230   709547
1   2023-01-03  2921.811279  2929.443629  2863.531191  2869.442976  1245178
2   2023-01-04  2924.722412  2935.928587  2899.619245  2917.707674  1231668
3   2023-01-05  2921.590820  2944.708677  2895.869822  2938.443816  1826057
4   2023-01-06  2833.751221  2913.163843  2823.559891  2911.796138  2488376
..         ...          ...          ...          ...          ...      ...
735 2025-12-24  3198.595947  3206.402196  3176.526789  3184.236572  1367708
736 2025-12-26  3161.010986  3199.559901  3153.108506  3192.910307  1176664
737 2025-12-29  3133.544434  3168.720313  3125.256324  3161.010531  2079473
738 2025-12-30  3129.015381  3148.964397  3121.980157  3132.099247  2807593
739 2025-12-31  3089.888184  3128.244400  3082.467565  3122.462063  3362634

     ticker
0    TCS.NS
1    TCS.NS
2    TCS.NS
3    TCS.NS
4    TCS.NS
..      ...
735  TCS.NS
736  TCS.NS
737  TCS.NS
738  TCS.NS
739  TCS.NS

[740 rows x 7 columns],           Date        Close         High          Low         Open   Volume  \
0   2023-01-02  1368.097534  1370.341789  1350.188427  1359.120516  3801140
1   2023-01-03  1366.795776  1375.862542  1360.107833  1364.371916  4551130
2   2023-01-04  1341.884521  1365.404262  1338.562960  1365.404262  7059590
3   2023-01-05  1324.289551  1351.849060  1318.948269  1351.849060  9868404
4   2023-01-06  1300.320923  1324.110018  1298.525519  1319.621510  6443714
..         ...          ...          ...          ...          ...      ...
735 2025-12-24  1628.167480  1632.278472  1617.498330  1625.818291  4271167
736 2025-12-26  1621.022095  1633.453168  1616.715267  1628.167521  2006491
737 2025-12-29  1609.863525  1637.662008  1602.424525  1622.881866  4062817
738 2025-12-30  1587.252808  1612.995794  1582.554548  1612.114833  9395937
739 2025-12-31  1581.184204  1594.104567  1575.115455  1586.665566  6538656

      ticker
0    INFY.NS
1    INFY.NS
2    INFY.NS
3    INFY.NS
4    INFY.NS
..       ...
735  INFY.NS
736  INFY.NS
737  INFY.NS
738  INFY.NS
739  INFY.NS

[740 rows x 7 columns],           Date       Close        High         Low        Open    Volume  \
0   2023-01-02  770.927124  776.157543  766.122780  770.122471   4381378
1   2023-01-03  775.968262  777.695961  767.850486  767.850486   8378030
2   2023-01-04  762.099426  778.997604  760.655719  773.909210  10351600
3   2023-01-05  757.200378  765.886195  752.325021  764.442488  10941436
4   2023-01-06  754.691711  761.649772  747.023585  758.289076   9092462
..         ...         ...         ...         ...         ...       ...
735 2025-12-24  980.975220  983.139437  976.843543  976.843543  13699996
736 2025-12-26  975.958191  980.975248  971.629816  979.794761   9360853
737 2025-12-29  975.564697  981.171968  971.137914  976.941883  13545749
738 2025-12-30  974.777771  978.811039  966.219311  974.089148  33155849
739 2025-12-31  975.072876  981.368710  971.531413  974.876118  10963454

          ticker
0    HDFCBANK.NS
1    HDFCBANK.NS
2    HDFCBANK.NS
3    HDFCBANK.NS
4    HDFCBANK.NS
..           ...
735  HDFCBANK.NS
736  HDFCBANK.NS
737  HDFCBANK.NS
738  HDFCBANK.NS
739  HDFCBANK.NS

[740 rows x 7 columns],           Date        Close         High          Low         Open    Volume  \
0   2023-01-02   873.285095   877.688039   865.108166   865.108166   4315403
1   2023-01-03   872.220642   876.672017   867.769326   869.462770   5846855
2   2023-01-04   870.043335   878.558988   865.882312   869.946590  12454582
3   2023-01-05   850.738159   873.817365   843.819205   871.785255  16547196
4   2023-01-06   841.980530   850.544555   832.690801   850.544555  14804613
..         ...          ...          ...          ...          ...       ...
735 2025-12-24  1348.432129  1356.761808  1346.250448  1352.398689   8955140
736 2025-12-26  1339.110596  1350.613595  1337.226456  1345.159575   2812144
737 2025-12-29  1332.070068  1344.366308  1330.285068  1340.796428   6057201
738 2025-12-30  1331.276611  1335.838131  1326.913371  1332.069972  18621277
739 2025-12-31  1331.673340  1338.713959  1328.301740  1331.574200   6150634

           ticker
0    ICICIBANK.NS
1    ICICIBANK.NS
2    ICICIBANK.NS
3    ICICIBANK.NS
4    ICICIBANK.NS
..            ...
735  ICICIBANK.NS
736  ICICIBANK.NS
737  ICICIBANK.NS
738  ICICIBANK.NS
739  ICICIBANK.NS

[740 rows x 7 columns]])

In [ ]:
processed_data.keys()

dict_keys(['RELIANCE.NS', 'TCS.NS', 'INFY.NS', 'HDFCBANK.NS', 'ICICIBANK.NS'])

In [ ]:
processed_data.values()

dict_values([          Date        Close         High          Low         Open    Volume  \
0   2023-01-02  1170.477783  1171.886424  1157.891000  1158.708901   5316175
1   2023-01-03  1161.912354  1169.160003  1157.709267  1165.547536   7658932
2   2023-01-04  1144.418213  1163.730055  1142.350684  1161.889687   9264891
3   2023-01-05  1142.373535  1152.529332  1137.806870  1146.667607  13637099
4   2023-01-06  1152.756348  1157.777455  1144.304622  1148.098818   6349597
..         ...          ...          ...          ...          ...       ...
735 2025-12-24  1551.028687  1568.448147  1546.449881  1565.461954   8815745
736 2025-12-26  1552.024048  1553.815812  1547.146696  1547.544758   2311495
737 2025-12-29  1538.486694  1550.929166  1536.495899  1547.743942   5972105
738 2025-12-30  1532.713379  1546.449794  1530.722584  1539.880194   8815884
739 2025-12-31  1563.172607  1569.742208  1533.907890  1533.907890   5771830

          ticker
0    RELIANCE.NS
1    RELIANCE.NS
2    RELIANCE.NS
3    RELIANCE.NS
4    RELIANCE.NS
..           ...
735  RELIANCE.NS
736  RELIANCE.NS
737  RELIANCE.NS
738  RELIANCE.NS
739  RELIANCE.NS

[740 rows x 7 columns],           Date        Close         High          Low         Open   Volume  \
0   2023-01-02  2877.781250  2882.546137  2854.619233  2877.384230   709547
1   2023-01-03  2921.811279  2929.443629  2863.531191  2869.442976  1245178
2   2023-01-04  2924.722412  2935.928587  2899.619245  2917.707674  1231668
3   2023-01-05  2921.590820  2944.708677  2895.869822  2938.443816  1826057
4   2023-01-06  2833.751221  2913.163843  2823.559891  2911.796138  2488376
..         ...          ...          ...          ...          ...      ...
735 2025-12-24  3198.595947  3206.402196  3176.526789  3184.236572  1367708
736 2025-12-26  3161.010986  3199.559901  3153.108506  3192.910307  1176664
737 2025-12-29  3133.544434  3168.720313  3125.256324  3161.010531  2079473
738 2025-12-30  3129.015381  3148.964397  3121.980157  3132.099247  2807593
739 2025-12-31  3089.888184  3128.244400  3082.467565  3122.462063  3362634

     ticker
0    TCS.NS
1    TCS.NS
2    TCS.NS
3    TCS.NS
4    TCS.NS
..      ...
735  TCS.NS
736  TCS.NS
737  TCS.NS
738  TCS.NS
739  TCS.NS

[740 rows x 7 columns],           Date        Close         High          Low         Open   Volume  \
0   2023-01-02  1368.097534  1370.341789  1350.188427  1359.120516  3801140
1   2023-01-03  1366.795776  1375.862542  1360.107833  1364.371916  4551130
2   2023-01-04  1341.884521  1365.404262  1338.562960  1365.404262  7059590
3   2023-01-05  1324.289551  1351.849060  1318.948269  1351.849060  9868404
4   2023-01-06  1300.320923  1324.110018  1298.525519  1319.621510  6443714
..         ...          ...          ...          ...          ...      ...
735 2025-12-24  1628.167480  1632.278472  1617.498330  1625.818291  4271167
736 2025-12-26  1621.022095  1633.453168  1616.715267  1628.167521  2006491
737 2025-12-29  1609.863525  1637.662008  1602.424525  1622.881866  4062817
738 2025-12-30  1587.252808  1612.995794  1582.554548  1612.114833  9395937
739 2025-12-31  1581.184204  1594.104567  1575.115455  1586.665566  6538656

      ticker
0    INFY.NS
1    INFY.NS
2    INFY.NS
3    INFY.NS
4    INFY.NS
..       ...
735  INFY.NS
736  INFY.NS
737  INFY.NS
738  INFY.NS
739  INFY.NS

[740 rows x 7 columns],           Date       Close        High         Low        Open    Volume  \
0   2023-01-02  770.927124  776.157543  766.122780  770.122471   4381378
1   2023-01-03  775.968262  777.695961  767.850486  767.850486   8378030
2   2023-01-04  762.099426  778.997604  760.655719  773.909210  10351600
3   2023-01-05  757.200378  765.886195  752.325021  764.442488  10941436
4   2023-01-06  754.691711  761.649772  747.023585  758.289076   9092462
..         ...         ...         ...         ...         ...       ...
735 2025-12-24  980.975220  983.139437  976.843543  976.843543  13699996
736 2025-12-26  975.958191  980.975248  971.629816  979.794761   9360853
737 2025-12-29  975.564697  981.171968  971.137914  976.941883  13545749
738 2025-12-30  974.777771  978.811039  966.219311  974.089148  33155849
739 2025-12-31  975.072876  981.368710  971.531413  974.876118  10963454

          ticker
0    HDFCBANK.NS
1    HDFCBANK.NS
2    HDFCBANK.NS
3    HDFCBANK.NS
4    HDFCBANK.NS
..           ...
735  HDFCBANK.NS
736  HDFCBANK.NS
737  HDFCBANK.NS
738  HDFCBANK.NS
739  HDFCBANK.NS

[740 rows x 7 columns],           Date        Close         High          Low         Open    Volume  \
0   2023-01-02   873.285095   877.688039   865.108166   865.108166   4315403
1   2023-01-03   872.220642   876.672017   867.769326   869.462770   5846855
2   2023-01-04   870.043335   878.558988   865.882312   869.946590  12454582
3   2023-01-05   850.738159   873.817365   843.819205   871.785255  16547196
4   2023-01-06   841.980530   850.544555   832.690801   850.544555  14804613
..         ...          ...          ...          ...          ...       ...
735 2025-12-24  1348.432129  1356.761808  1346.250448  1352.398689   8955140
736 2025-12-26  1339.110596  1350.613595  1337.226456  1345.159575   2812144
737 2025-12-29  1332.070068  1344.366308  1330.285068  1340.796428   6057201
738 2025-12-30  1331.276611  1335.838131  1326.913371  1332.069972  18621277
739 2025-12-31  1331.673340  1338.713959  1328.301740  1331.574200   6150634

           ticker
0    ICICIBANK.NS
1    ICICIBANK.NS
2    ICICIBANK.NS
3    ICICIBANK.NS
4    ICICIBANK.NS
..            ...
735  ICICIBANK.NS
736  ICICIBANK.NS
737  ICICIBANK.NS
738  ICICIBANK.NS
739  ICICIBANK.NS

[740 rows x 7 columns]])

In [ ]:
master_data = pd.concat(processed_data.values(), ignore_index = True)

In [ ]:
master_data.head()

,Date,Close,High,Low,Open,Volume,ticker
0,2023-01-02,1170.477783,1171.886424,1157.891000,1158.708901,5316175,RELIANCE.NS
1,2023-01-03,1161.912354,1169.160003,1157.709267,1165.547536,7658932,RELIANCE.NS
2,2023-01-04,1144.418213,1163.730055,1142.350684,1161.889687,9264891,RELIANCE.NS
3,2023-01-05,1142.373535,1152.529332,1137.806870,1146.667607,13637099,RELIANCE.NS
4,2023-01-06,1152.756348,1157.777455,1144.304622,1148.098818,6349597,RELIANCE.NS

In [ ]:
master_data.shape

(3700, 7)

In [ ]:
master_data.isnull().sum()

Date      0
Close     0
High      0
Low       0
Open      0
Volume    0
ticker    0
dtype: int64

In [ ]:
master_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3700 entries, 0 to 3699
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    3700 non-null   datetime64[ns]
 1   Close   3700 non-null   float64
 2   High    3700 non-null   float64
 3   Low     3700 non-null   float64
 4   Open    3700 non-null   float64
 5   Volume  3700 non-null   int64
 6   ticker  3700 non-null   object
dtypes: datetime64[ns](1), float64(4), int64(1), object(1)
memory usage: 202.5+ KB

In [ ]:
master_data.head()

,Date,Close,High,Low,Open,Volume,ticker
0,2023-01-02,1170.477783,1171.886424,1157.891000,1158.708901,5316175,RELIANCE.NS
1,2023-01-03,1161.912354,1169.160003,1157.709267,1165.547536,7658932,RELIANCE.NS
2,2023-01-04,1144.418213,1163.730055,1142.350684,1161.889687,9264891,RELIANCE.NS
3,2023-01-05,1142.373535,1152.529332,1137.806870,1146.667607,13637099,RELIANCE.NS
4,2023-01-06,1152.756348,1157.777455,1144.304622,1148.098818,6349597,RELIANCE.NS

In [ ]:
master_data = master_data.sort_values(by = ["ticker","Date"])

In [ ]:
master_data.reset_index(drop = True)

,Date,Close,High,Low,Open,Volume,ticker
0,2023-01-02,770.927124,776.157543,766.122780,770.122471,4381378,HDFCBANK.NS
1,2023-01-03,775.968262,777.695961,767.850486,767.850486,8378030,HDFCBANK.NS
2,2023-01-04,762.099426,778.997604,760.655719,773.909210,10351600,HDFCBANK.NS
3,2023-01-05,757.200378,765.886195,752.325021,764.442488,10941436,HDFCBANK.NS
4,2023-01-06,754.691711,761.649772,747.023585,758.289076,9092462,HDFCBANK.NS
...,...,...,...,...,...,...,...
3695,2025-12-24,3198.595947,3206.402196,3176.526789,3184.236572,1367708,TCS.NS
3696,2025-12-26,3161.010986,3199.559901,3153.108506,3192.910307,1176664,TCS.NS
3697,2025-12-29,3133.544434,3168.720313,3125.256324,3161.010531,2079473,TCS.NS
3698,2025-12-30,3129.015381,3148.964397,3121.980157,3132.099247,2807593,TCS.NS
3699,2025-12-31,3089.888184,3128.244400,3082.467565,3122.462063,3362634,TCS.NS

In [ ]:
master_data = master_data.reset_index(drop = True)

In [ ]:
master_data.groupby("ticker")

In [ ]:
master_data.groupby("ticker").groups.keys()

dict_keys(['HDFCBANK.NS', 'ICICIBANK.NS', 'INFY.NS', 'RELIANCE.NS', 'TCS.NS'])

In [ ]:
master_data["Daily_Return"] = (master_data.groupby("ticker")["Close"].pct_change())

In [ ]:
master_data.head(15)

,Date,Close,High,Low,Open,Volume,ticker,Daily_Return
0,2023-01-02,770.927124,776.157543,766.122780,770.122471,4381378,HDFCBANK.NS,NaN
1,2023-01-03,775.968262,777.695961,767.850486,767.850486,8378030,HDFCBANK.NS,0.006539
2,2023-01-04,762.099426,778.997604,760.655719,773.909210,10351600,HDFCBANK.NS,-0.017873
3,2023-01-05,757.200378,765.886195,752.325021,764.442488,10941436,HDFCBANK.NS,-0.006428
4,2023-01-06,754.691711,761.649772,747.023585,758.289076,9092462,HDFCBANK.NS,-0.003313
5,2023-01-09,756.158997,762.809432,752.608954,755.448988,10729340,HDFCBANK.NS,0.001944
6,2023-01-10,742.337585,757.342409,740.775544,757.342409,16371766,HDFCBANK.NS,-0.018278
7,2023-01-11,753.035034,756.395730,738.408847,742.171869,15195798,HDFCBANK.NS,0.014410
8,2023-01-12,757.058411,759.188436,749.839991,751.567690,9250070,HDFCBANK.NS,0.005343
9,2023-01-13,757.650085,762.028471,750.715658,756.750730,9244546,HDFCBANK.NS,0.000782
10,2023-01-16,750.384338,767.424542,748.017643,764.442484,14748094,HDFCBANK.NS,-0.009590
11,2023-01-17,761.555115,762.549115,746.692259,752.514352,10786354,HDFCBANK.NS,0.014887
12,2023-01-18,774.997925,777.033248,757.200333,759.709053,19090642,HDFCBANK.NS,0.017652
13,2023-01-19,778.216614,781.009325,772.962563,774.855919,11172162,HDFCBANK.NS,0.004153
14,2023-01-20,786.192383,790.002785,777.885318,778.216632,18843404,HDFCBANK.NS,0.010249

In [ ]:
master_data["Cumulative_Return"] = ((1+master_data["Daily_Return"].groupby(master_data['ticker']).cumprod()))

In [ ]:
master_data.head()

,Date,Close,High,Low,Open,Volume,ticker,Daily_Return,Cumulative_Return
0,2023-01-02,770.927124,776.157543,766.122780,770.122471,4381378,HDFCBANK.NS,NaN,NaN
1,2023-01-03,775.968262,777.695961,767.850486,767.850486,8378030,HDFCBANK.NS,0.006539,1.006539
2,2023-01-04,762.099426,778.997604,760.655719,773.909210,10351600,HDFCBANK.NS,-0.017873,0.999883
3,2023-01-05,757.200378,765.886195,752.325021,764.442488,10941436,HDFCBANK.NS,-0.006428,1.000001
4,2023-01-06,754.691711,761.649772,747.023585,758.289076,9092462,HDFCBANK.NS,-0.003313,1.000000

In [ ]:
master_data.reset_index(drop= True)

,Date,Close,High,Low,Open,Volume,ticker,Daily_Return,Cumulative_Return
0,2023-01-02,770.927124,776.157543,766.122780,770.122471,4381378,HDFCBANK.NS,NaN,NaN
1,2023-01-03,775.968262,777.695961,767.850486,767.850486,8378030,HDFCBANK.NS,0.006539,1.006539
2,2023-01-04,762.099426,778.997604,760.655719,773.909210,10351600,HDFCBANK.NS,-0.017873,0.999883
3,2023-01-05,757.200378,765.886195,752.325021,764.442488,10941436,HDFCBANK.NS,-0.006428,1.000001
4,2023-01-06,754.691711,761.649772,747.023585,758.289076,9092462,HDFCBANK.NS,-0.003313,1.000000
...,...,...,...,...,...,...,...,...,...
3695,2025-12-24,3198.595947,3206.402196,3176.526789,3184.236572,1367708,TCS.NS,0.002719,1.000000
3696,2025-12-26,3161.010986,3199.559901,3153.108506,3192.910307,1176664,TCS.NS,-0.011750,1.000000
3697,2025-12-29,3133.544434,3168.720313,3125.256324,3161.010531,2079473,TCS.NS,-0.008689,1.000000
3698,2025-12-30,3129.015381,3148.964397,3121.980157,3132.099247,2807593,TCS.NS,-0.001445,1.000000
3699,2025-12-31,3089.888184,3128.244400,3082.467565,3122.462063,3362634,TCS.NS,-0.012505,1.000000

In [ ]:
portfolio_metadata = pd.DataFrame({'ticker':['RELIANCE.NS','TCS.NS','INFY.NS','HDFCBANK.NS','ICICIBANK.NS'], 'weight':[0.3,0.25,0.2,0.15,0.1], 'Sector': ["Energy","Information Technology","Information Technology","Financial Services","Financial Services"]})

In [ ]:
portfolio_metadata

         ticker  weight                  Sector
0   RELIANCE.NS    0.30                  Energy
1        TCS.NS    0.25  Information Technology
2       INFY.NS    0.20  Information Technology
3   HDFCBANK.NS    0.15      Financial Services
4  ICICIBANK.NS    0.10      Financial Services

In [ ]:
portfolio_metadata.columns

Index(['ticker', 'weight', 'Sector'], dtype='object')

In [ ]:
master_data = master_data.merge(portfolio_metadata, on = 'ticker', how = 'left')

In [ ]:
master_data.head()

,Date,Close,High,Low,Open,Volume,ticker,Daily_Return,Cumulative_Return,weight,Sector
0,2023-01-02,770.927124,776.157543,766.122780,770.122471,4381378,HDFCBANK.NS,NaN,NaN,0.15,Financial Services
1,2023-01-03,775.968262,777.695961,767.850486,767.850486,8378030,HDFCBANK.NS,0.006539,1.006539,0.15,Financial Services
2,2023-01-04,762.099426,778.997604,760.655719,773.909210,10351600,HDFCBANK.NS,-0.017873,0.999883,0.15,Financial Services
3,2023-01-05,757.200378,765.886195,752.325021,764.442488,10941436,HDFCBANK.NS,-0.006428,1.000001,0.15,Financial Services
4,2023-01-06,754.691711,761.649772,747.023585,758.289076,9092462,HDFCBANK.NS,-0.003313,1.000000,0.15,Financial Services

In [ ]:
master_data['Weighted_Return'] = (master_data['Daily_Return']*master_data['weight'])

In [ ]:
master_data.head()

,Date,Close,High,Low,Open,Volume,ticker,Daily_Return,Cumulative_Return,weight,Sector,Weighted_Return
0,2023-01-02,770.927124,776.157543,766.122780,770.122471,4381378,HDFCBANK.NS,NaN,NaN,0.15,Financial Services,NaN
1,2023-01-03,775.968262,777.695961,767.850486,767.850486,8378030,HDFCBANK.NS,0.006539,1.006539,0.15,Financial Services,0.000981
2,2023-01-04,762.099426,778.997604,760.655719,773.909210,10351600,HDFCBANK.NS,-0.017873,0.999883,0.15,Financial Services,-0.002681
3,2023-01-05,757.200378,765.886195,752.325021,764.442488,10941436,HDFCBANK.NS,-0.006428,1.000001,0.15,Financial Services,-0.000964
4,2023-01-06,754.691711,761.649772,747.023585,758.289076,9092462,HDFCBANK.NS,-0.003313,1.000000,0.15,Financial Services,-0.000497

In [ ]:
portfolio_returns = (master_data.groupby("Date")["Weighted_Return"].sum().reset_index())

In [ ]:
portfolio_returns

          Date  Weighted_Return
0   2023-01-02         0.000000
1   2023-01-03         0.002298
2   2023-01-04        -0.010844
3   2023-01-05        -0.006609
4   2023-01-06        -0.009936
..         ...              ...
735 2025-12-24        -0.002440
736 2025-12-26        -0.005081
737 2025-12-29        -0.006752
738 2025-12-30        -0.004477
739 2025-12-31         0.002146

[740 rows x 2 columns]

In [ ]:
portfolio_returns.columns = ["Date", "Portfolio_Daily_Return"]

In [ ]:
portfolio_returns.head()

        Date  Portfolio_Daily_Return
0 2023-01-02                0.000000
1 2023-01-03                0.002298
2 2023-01-04               -0.010844
3 2023-01-05               -0.006609
4 2023-01-06               -0.009936

In [ ]:
portfolio_returns["Portfolio_Cumulative_Return"] = ((1+portfolio_returns["Portfolio_Daily_Return"]).cumprod())

In [ ]:
portfolio_returns.head()

        Date  Portfolio_Daily_Return  Portfolio_Cumulative_Return
0 2023-01-02                0.000000                     1.000000
1 2023-01-03                0.002298                     1.002298
2 2023-01-04               -0.010844                     0.991430
3 2023-01-05               -0.006609                     0.984877
4 2023-01-06               -0.009936                     0.975091

In [ ]:
portfolio_returns['Portfolio_Cumulative_Percent'] = (portfolio_returns["Portfolio_Cumulative_Return"]-1)

In [ ]:
portfolio_returns.head()

,Date,Portfolio_Daily_Return,Portfolio_Cumulative_Return,Portfolio_Cumulative_Percent
0,2023-01-02,0.000000,1.000000,0.000000
1,2023-01-03,0.002298,1.002298,0.002298
2,2023-01-04,-0.010844,0.991430,-0.008570
3,2023-01-05,-0.006609,0.984877,-0.015123
4,2023-01-06,-0.009936,0.975091,-0.024909

In [ ]:
initial_investment= 50000000

In [ ]:
portfolio_returns["Portfolio_Value"] = (initial_investment*portfolio_returns["Portfolio_Cumulative_Return"])

In [ ]:
portfolio_returns.head()

,Date,Portfolio_Daily_Return,Portfolio_Cumulative_Return,Portfolio_Cumulative_Percent,Portfolio_Value
0,2023-01-02,0.000000,1.000000,0.000000,5.000000e+07
1,2023-01-03,0.002298,1.002298,0.002298,5.011491e+07
2,2023-01-04,-0.010844,0.991430,-0.008570,4.957149e+07
3,2023-01-05,-0.006609,0.984877,-0.015123,4.924386e+07
4,2023-01-06,-0.009936,0.975091,-0.024909,4.875457e+07

In [ ]:
daily_variance = portfolio_returns["Portfolio_Daily_Return"].var()

In [ ]:
daily_variance

7.867634573426398e-05

In [ ]:
daily_volatility = portfolio_returns['Portfolio_Daily_Return'].std()

In [ ]:
daily_volatility*100

0.886996875610416

In [ ]:
annual_volatility = daily_volatility*252**0.5

In [ ]:
annual_volatility*100

14.080638879338721

In [ ]:
risk_summary = pd.DataFrame({"Metric":["Daily_Variance","Daily_Volatility","Annualized_Volatility"], "Value": [daily_variance, daily_volatility, annual_volatility]})

In [ ]:
risk_summary

                  Metric     Value
0         Daily_Variance  0.000079
1       Daily_Volatility  0.008870
2  Annualized_Volatility  0.140806

In [ ]:
return_matrix = master_data.pivot(index = "Date", columns = "ticker", values = "Close")

In [ ]:
return_matrix

ticker      HDFCBANK.NS  ICICIBANK.NS      INFY.NS  RELIANCE.NS       TCS.NS
Date
2023-01-02   770.927124    873.285095  1368.097534  1170.477783  2877.781250
2023-01-03   775.968262    872.220642  1366.795776  1161.912354  2921.811279
2023-01-04   762.099426    870.043335  1341.884521  1144.418213  2924.722412
2023-01-05   757.200378    850.738159  1324.289551  1142.373535  2921.590820
2023-01-06   754.691711    841.980530  1300.320923  1152.756348  2833.751221
...                 ...           ...          ...          ...          ...
2025-12-24   980.975220   1348.432129  1628.167480  1551.028687  3198.595947
2025-12-26   975.958191   1339.110596  1621.022095  1552.024048  3161.010986
2025-12-29   975.564697   1332.070068  1609.863525  1538.486694  3133.544434
2025-12-30   974.777771   1331.276611  1587.252808  1532.713379  3129.015381
2025-12-31   975.072876   1331.673340  1581.184204  1563.172607  3089.888184

[740 rows x 5 columns]

In [ ]:
return_matrix = return_matrix.pct_change()

In [ ]:
return_matrix

ticker      HDFCBANK.NS  ICICIBANK.NS   INFY.NS  RELIANCE.NS    TCS.NS
Date
2023-01-02          NaN           NaN       NaN          NaN       NaN
2023-01-03     0.006539     -0.001219 -0.000952    -0.007318  0.015300
2023-01-04    -0.017873     -0.002496 -0.018226    -0.015056  0.000996
2023-01-05    -0.006428     -0.022189 -0.013112    -0.001787 -0.001071
2023-01-06    -0.003313     -0.010294 -0.018099     0.009089 -0.030066
...                 ...           ...       ...          ...       ...
2025-12-24     0.000602     -0.002348 -0.002937    -0.007958  0.002719
2025-12-26    -0.005114     -0.006913 -0.004389     0.000642 -0.011750
2025-12-29    -0.000403     -0.005258 -0.006884    -0.008722 -0.008689
2025-12-30    -0.000807     -0.000596 -0.014045    -0.003753 -0.001445
2025-12-31     0.000303      0.000298 -0.003823     0.019873 -0.012505

[740 rows x 5 columns]

In [ ]:
return_matrix = return_matrix.dropna(axis = 0)

In [ ]:
return_matrix

ticker      HDFCBANK.NS  ICICIBANK.NS   INFY.NS  RELIANCE.NS    TCS.NS
Date
2023-01-03     0.006539     -0.001219 -0.000952    -0.007318  0.015300
2023-01-04    -0.017873     -0.002496 -0.018226    -0.015056  0.000996
2023-01-05    -0.006428     -0.022189 -0.013112    -0.001787 -0.001071
2023-01-06    -0.003313     -0.010294 -0.018099     0.009089 -0.030066
2023-01-09     0.001944      0.003735  0.024819     0.023611  0.033753
...                 ...           ...       ...          ...       ...
2025-12-24     0.000602     -0.002348 -0.002937    -0.007958  0.002719
2025-12-26    -0.005114     -0.006913 -0.004389     0.000642 -0.011750
2025-12-29    -0.000403     -0.005258 -0.006884    -0.008722 -0.008689
2025-12-30    -0.000807     -0.000596 -0.014045    -0.003753 -0.001445
2025-12-31     0.000303      0.000298 -0.003823     0.019873 -0.012505

[739 rows x 5 columns]

In [ ]:
covariance_matrix = return_matrix.cov()

In [ ]:
covariance_matrix

ticker        HDFCBANK.NS  ICICIBANK.NS   INFY.NS  RELIANCE.NS    TCS.NS
ticker
HDFCBANK.NS      0.000135      0.000060  0.000034     0.000053  0.000021
ICICIBANK.NS     0.000060      0.000124  0.000039     0.000053  0.000025
INFY.NS          0.000034      0.000039  0.000224     0.000048  0.000131
RELIANCE.NS      0.000053      0.000053  0.000048     0.000160  0.000043
TCS.NS           0.000021      0.000025  0.000131     0.000043  0.000155

In [ ]:
correlation_matrix = return_matrix.corr()

In [ ]:
correlation_matrix

ticker        HDFCBANK.NS  ICICIBANK.NS   INFY.NS  RELIANCE.NS    TCS.NS
ticker
HDFCBANK.NS      1.000000      0.460413  0.192730     0.362564  0.143191
ICICIBANK.NS     0.460413      1.000000  0.233035     0.379771  0.184043
INFY.NS          0.192730      0.233035  1.000000     0.251968  0.702550
RELIANCE.NS      0.362564      0.379771  0.251968     1.000000  0.275337
TCS.NS           0.143191      0.184043  0.702550     0.275337  1.000000

In [ ]:
portfolio_metadata

         ticker  weight                  Sector
0   RELIANCE.NS    0.30                  Energy
1        TCS.NS    0.25  Information Technology
2       INFY.NS    0.20  Information Technology
3   HDFCBANK.NS    0.15      Financial Services
4  ICICIBANK.NS    0.10      Financial Services

In [ ]:
covariance_matrix

ticker        HDFCBANK.NS  ICICIBANK.NS   INFY.NS  RELIANCE.NS    TCS.NS
ticker
HDFCBANK.NS      0.000135      0.000060  0.000034     0.000053  0.000021
ICICIBANK.NS     0.000060      0.000124  0.000039     0.000053  0.000025
INFY.NS          0.000034      0.000039  0.000224     0.000048  0.000131
RELIANCE.NS      0.000053      0.000053  0.000048     0.000160  0.000043
TCS.NS           0.000021      0.000025  0.000131     0.000043  0.000155

In [ ]:
weights = portfolio_metadata.set_index("ticker")["weight"]

In [ ]:
weights

ticker
RELIANCE.NS     0.30
TCS.NS          0.25
INFY.NS         0.20
HDFCBANK.NS     0.15
ICICIBANK.NS    0.10
Name: weight, dtype: float64

In [ ]:
weights = weights.reindex(covariance_matrix.columns)

In [ ]:
weights

ticker
HDFCBANK.NS     0.15
ICICIBANK.NS    0.10
INFY.NS         0.20
RELIANCE.NS     0.30
TCS.NS          0.25
Name: weight, dtype: float64

In [ ]:
weights.values

array([0.15, 0.1 , 0.2 , 0.3 , 0.25])

In [ ]:
portfolio_variance =(weights.values.T @covariance_matrix.values @weights.values)

In [ ]:
portfolio_variance

np.float64(7.878277058725701e-05)

In [ ]:
portfolio_volatility = np.sqrt(portfolio_variance)

In [ ]:
portfolio_volatility*100

np.float64(0.8875965896017008)

In [ ]:
portfolio_annual_volatility = portfolio_volatility*np.sqrt(252)

In [ ]:
portfolio_annual_volatility*100

np.float64(14.090159043810957)

In [ ]:
expected_daily_return = return_matrix.mean()

In [ ]:
expected_daily_return

ticker
HDFCBANK.NS     0.000386
ICICIBANK.NS    0.000633
INFY.NS         0.000308
RELIANCE.NS     0.000471
TCS.NS          0.000173
dtype: float64

In [ ]:
expected_annual_return = expected_daily_return*252

In [ ]:
expected_annual_return

ticker
HDFCBANK.NS     0.097274
ICICIBANK.NS    0.159480
INFY.NS         0.077573
RELIANCE.NS     0.118729
TCS.NS          0.043655
dtype: float64

In [ ]:
expected_annual_return = expected_annual_return.reindex(weights.index)

In [ ]:
expected_annual_return

ticker
HDFCBANK.NS     0.097274
ICICIBANK.NS    0.159480
INFY.NS         0.077573
RELIANCE.NS     0.118729
TCS.NS          0.043655
dtype: float64

In [ ]:
individual_expected_return = (weights*expected_annual_return)

In [ ]:
portfolio_expected_return = individual_expected_return.sum()

In [ ]:
portfolio_expected_return

np.float64(0.09258613055285496)

In [ ]:
portfolio_expected_return*100

np.float64(9.258613055285496)

In [ ]:
risk_free_rate = 0.067

In [ ]:
sharpe_ratio = (portfolio_expected_return - risk_free_rate)/portfolio_annual_volatility

In [ ]:
sharpe_ratio

np.float64(0.1815886568299139)

In [ ]:
benchmark_data = yf.download("^NSEI", start = start_date, end = end_date, auto_adjust = True)

[*********************100%***********************]  1 of 1 completed

In [ ]:
benchmark_data['Benchmark_Return'] = benchmark_data['Close'].fillna(0).pct_change()

In [ ]:
benchmark_data.dropna()

Price,Close,High,Low,Open,Volume,Benchmark_Return
Ticker,^NSEI,^NSEI,^NSEI,^NSEI,^NSEI,
Date,,,,,,
2023-01-03,18232.550781,18251.949219,18149.800781,18163.199219,208700,0.001929
2023-01-04,18042.949219,18243.000000,18020.599609,18230.650391,235200,-0.010399
2023-01-05,17992.150391,18120.300781,17892.599609,18101.949219,269900,-0.002815
2023-01-06,17859.449219,18047.400391,17795.550781,18008.050781,238200,-0.007376
2023-01-09,18101.199219,18141.400391,17936.150391,17952.550781,257200,0.013536
...,...,...,...,...,...,...
2025-12-24,26142.099609,26236.400391,26123.000000,26170.650391,188800,-0.001339
2025-12-26,26042.300781,26144.199219,26008.599609,26121.250000,142200,-0.003818
2025-12-29,25942.099609,26106.800781,25920.300781,26063.349609,234300,-0.003848
2025-12-30,25938.849609,25976.750000,25878.000000,25940.900391,396900,-0.000125
2025-12-31,26129.599609,26187.949219,25969.000000,25971.050781,246300,0.007354

In [ ]:
benchmark_data["Benchmark_Cumulative_Return"] = ((1+benchmark_data["Benchmark_Return"].fillna(0)).cumprod())

In [ ]:
portfolio_returns

,Date,Portfolio_Daily_Return,Portfolio_Cumulative_Return,Portfolio_Cumulative_Percent,Portfolio_Value
0,2023-01-02,0.000000,1.000000,0.000000,5.000000e+07
1,2023-01-03,0.002298,1.002298,0.002298,5.011491e+07
2,2023-01-04,-0.010844,0.991430,-0.008570,4.957149e+07
3,2023-01-05,-0.006609,0.984877,-0.015123,4.924386e+07
4,2023-01-06,-0.009936,0.975091,-0.024909,4.875457e+07
...,...,...,...,...,...
735,2025-12-24,-0.002440,1.292598,0.292598,6.462989e+07
736,2025-12-26,-0.005081,1.286030,0.286030,6.430149e+07
737,2025-12-29,-0.006752,1.277346,0.277346,6.386732e+07
738,2025-12-30,-0.004477,1.271628,0.271628,6.358141e+07
739,2025-12-31,0.002146,1.274357,0.274357,6.371787e+07

In [ ]:
benchmark_data.reset_index()

Price,Date,Close,High,Low,Open,Volume,Benchmark_Return,Benchmark_Cumulative_Return
Ticker,,^NSEI,^NSEI,^NSEI,^NSEI,^NSEI,,
0,2023-01-02,18197.449219,18215.150391,18086.500000,18131.699219,256100,NaN,1.000000
1,2023-01-03,18232.550781,18251.949219,18149.800781,18163.199219,208700,0.001929,1.001929
2,2023-01-04,18042.949219,18243.000000,18020.599609,18230.650391,235200,-0.010399,0.991510
3,2023-01-05,17992.150391,18120.300781,17892.599609,18101.949219,269900,-0.002815,0.988718
4,2023-01-06,17859.449219,18047.400391,17795.550781,18008.050781,238200,-0.007376,0.981426
...,...,...,...,...,...,...,...,...
735,2025-12-24,26142.099609,26236.400391,26123.000000,26170.650391,188800,-0.001339,1.436580
736,2025-12-26,26042.300781,26144.199219,26008.599609,26121.250000,142200,-0.003818,1.431096
737,2025-12-29,25942.099609,26106.800781,25920.300781,26063.349609,234300,-0.003848,1.425590
738,2025-12-30,25938.849609,25976.750000,25878.000000,25940.900391,396900,-0.000125,1.425411
739,2025-12-31,26129.599609,26187.949219,25969.000000,25971.050781,246300,0.007354,1.435894

In [ ]:
benchmark_data = benchmark_data.reset_index()

In [ ]:
benchmark_data

Price,Date,Close,High,Low,Open,Volume,Benchmark_Return,Benchmark_Cumulative_Return
Ticker,,^NSEI,^NSEI,^NSEI,^NSEI,^NSEI,,
0,2023-01-02,18197.449219,18215.150391,18086.500000,18131.699219,256100,NaN,1.000000
1,2023-01-03,18232.550781,18251.949219,18149.800781,18163.199219,208700,0.001929,1.001929
2,2023-01-04,18042.949219,18243.000000,18020.599609,18230.650391,235200,-0.010399,0.991510
3,2023-01-05,17992.150391,18120.300781,17892.599609,18101.949219,269900,-0.002815,0.988718
4,2023-01-06,17859.449219,18047.400391,17795.550781,18008.050781,238200,-0.007376,0.981426
...,...,...,...,...,...,...,...,...
735,2025-12-24,26142.099609,26236.400391,26123.000000,26170.650391,188800,-0.001339,1.436580
736,2025-12-26,26042.300781,26144.199219,26008.599609,26121.250000,142200,-0.003818,1.431096
737,2025-12-29,25942.099609,26106.800781,25920.300781,26063.349609,234300,-0.003848,1.425590
738,2025-12-30,25938.849609,25976.750000,25878.000000,25940.900391,396900,-0.000125,1.425411
739,2025-12-31,26129.599609,26187.949219,25969.000000,25971.050781,246300,0.007354,1.435894

In [ ]:
#Now compare the Portfolio Cumulative return and benchmark cumulative return

In [ ]:
benchmark_return = benchmark_data[["Date","Benchmark_Return", "Benchmark_Cumulative_Return"]]

In [ ]:
benchmark_return

Price        Date Benchmark_Return Benchmark_Cumulative_Return
Ticker
0      2023-01-02              NaN                    1.000000
1      2023-01-03         0.001929                    1.001929
2      2023-01-04        -0.010399                    0.991510
3      2023-01-05        -0.002815                    0.988718
4      2023-01-06        -0.007376                    0.981426
..            ...              ...                         ...
735    2025-12-24        -0.001339                    1.436580
736    2025-12-26        -0.003818                    1.431096
737    2025-12-29        -0.003848                    1.425590
738    2025-12-30        -0.000125                    1.425411
739    2025-12-31         0.007354                    1.435894

[740 rows x 3 columns]

In [ ]:
benchmark_return.columns = ["Date","Benchmark_Return","Benchmark_Cumulative_Return"]

In [ ]:
portfolio_comparison = portfolio_returns[["Date","Portfolio_Cumulative_Return"]].merge(benchmark_return, on = "Date", how = "inner")

In [ ]:
portfolio_comparison

,Date,Portfolio_Cumulative_Return,Benchmark_Return,Benchmark_Cumulative_Return
0,2023-01-02,1.000000,NaN,1.000000
1,2023-01-03,1.002298,0.001929,1.001929
2,2023-01-04,0.991430,-0.010399,0.991510
3,2023-01-05,0.984877,-0.002815,0.988718
4,2023-01-06,0.975091,-0.007376,0.981426
...,...,...,...,...
735,2025-12-24,1.292598,-0.001339,1.436580
736,2025-12-26,1.286030,-0.003818,1.431096
737,2025-12-29,1.277346,-0.003848,1.425590
738,2025-12-30,1.271628,-0.000125,1.425411
739,2025-12-31,1.274357,0.007354,1.435894

In [ ]:
portfolio_comparison = portfolio_returns[["Date","Portfolio_Daily_Return","Portfolio_Cumulative_Return"]].merge(benchmark_return,on = "Date", how = "inner")

In [ ]:
portfolio_comparison.dropna()

,Date,Portfolio_Daily_Return,Portfolio_Cumulative_Return,Benchmark_Return,Benchmark_Cumulative_Return
1,2023-01-03,0.002298,1.002298,0.001929,1.001929
2,2023-01-04,-0.010844,0.991430,-0.010399,0.991510
3,2023-01-05,-0.006609,0.984877,-0.002815,0.988718
4,2023-01-06,-0.009936,0.975091,-0.007376,0.981426
5,2023-01-09,0.021151,0.995715,0.013536,0.994711
...,...,...,...,...,...
735,2025-12-24,-0.002440,1.292598,-0.001339,1.436580
736,2025-12-26,-0.005081,1.286030,-0.003818,1.431096
737,2025-12-29,-0.006752,1.277346,-0.003848,1.425590
738,2025-12-30,-0.004477,1.271628,-0.000125,1.425411
739,2025-12-31,0.002146,1.274357,0.007354,1.435894

In [ ]:
beta = portfolio_comparison["Portfolio_Daily_Return"].cov(portfolio_comparison["Benchmark_Return"]/portfolio_comparison["Benchmark_Return"].var())

In [ ]:
beta

np.float64(1.0013107359300644)

In [ ]:
years = (benchmark_return["Date"].iloc[-1] - benchmark_return["Date"].iloc[0]).days/365.25

In [ ]:
years

2.9952087611225187

In [ ]:
#benchmark CAGR
benchmark_cagr = (benchmark_return['Benchmark_Cumulative_Return'].iloc[-1]/benchmark_return['Benchmark_Cumulative_Return'].iloc[0])**(1/years)-1

In [ ]:
benchmark_cagr*100

np.float64(12.838644120771736)

In [ ]:
portfolio_cagr = (portfolio_returns["Portfolio_Cumulative_Return"].iloc[-1]/portfolio_returns["Portfolio_Cumulative_Return"].iloc[0])**(1/years)-1

In [ ]:
portfolio_cagr*100

np.float64(8.430939555184679)

In [ ]:
required_return = risk_free_rate+beta*(benchmark_cagr-risk_free_rate)

In [ ]:
alpha = portfolio_cagr - required_return
alpha

np.float64(-0.044157507069980284)

In [ ]:
alpha*100

np.float64(-4.415750706998028)

In [ ]:
treynor_ratio = (portfolio_cagr - risk_free_rate)/ beta

In [ ]:
treynor_ratio*100

np.float64(1.7286737204279565)

In [ ]:
benchmark_treynor = (benchmark_cagr - risk_free_rate)

In [ ]:
benchmark_treynor *100

np.float64(6.138644120771736)

In [ ]:
performance_summary = {"Cumulative Summary": portfolio_returns["Portfolio_Cumulative_Return"].iloc[-1]-1,'CAGR': portfolio_cagr, "Annualized_Volatility": portfolio_annual_volatility, "Sharpe Ratio": sharpe_ratio, "Beta": beta,"Jensen Alpha":alpha, "Treynor Ratio": treynor_ratio}

In [ ]:
performance_summary_df = pd.DataFrame(performance_summary.items(), columns = ["Metric","Portfolio"])

In [ ]:
performance_summary_df

                  Metric  Portfolio
0     Cumulative Summary   0.274357
1                   CAGR   0.084309
2  Annualized_Volatility   0.140902
3           Sharpe Ratio   0.181589
4                   Beta   1.001311
5           Jensen Alpha  -0.044158
6          Treynor Ratio   0.017287

In [ ]:
benchmark_metrics = {"Cumulative Summary": benchmark_return["Benchmark_Cumulative_Return"].iloc[-1]-1,"CAGR": benchmark_cagr, "Beta": 1, "Alpha": 0, "Treynor Ratio": benchmark_treynor}

In [ ]:
benchmark_summary_df = pd.DataFrame(benchmark_metrics.items(), columns = ["Metric","Benchmark"])

In [ ]:
performance_summary_df= performance_summary_df.merge(benchmark_summary_df, on = "Metric", how = "left")

In [ ]:
performance_summary_df

                  Metric  Portfolio  Benchmark
0     Cumulative Summary   0.274357   0.435894
1                   CAGR   0.084309   0.128386
2  Annualized_Volatility   0.140902        NaN
3           Sharpe Ratio   0.181589        NaN
4                   Beta   1.001311   1.000000
5           Jensen Alpha  -0.044158        NaN
6          Treynor Ratio   0.017287   0.061386

In [ ]:
performance_summary_df.to_csv("performance_summary.csv", index=False)

In [ ]:
import zipfile
from google.colab import files

files_to_zip = [
    "master_data.csv",
    "portfolio_returns.csv",
    "benchmark_return.csv",
    "portfolio_comparison.csv",
    "performance_summary.csv",
    "correlation_matrix.csv",
    "covariance_matrix.csv"
]

with zipfile.ZipFile("portfolio_powerbi_data.zip", "w") as zipf:
    for file in files_to_zip:
        zipf.write(file)

files.download("portfolio_powerbi_data.zip")