In [135]:
import pandas as pd
import yfinance as yf
import numpy as np

In [136]:
portfolio = ['RELIANCE.NS','TCS.NS','INFY.NS','HDFCBANK.NS','ICICIBANK.NS']

In [137]:
start_date = '2023-01-01'
end_date = '2026-01-01'

In [138]:
for stock in portfolio:
  yf.download(stock, start=start_date, end= end_date)

/tmp/ipykernel_3881/3973490860.py:2: FutureWarning: YF.download() has changed argument auto_adjust default to True
  yf.download(stock, start=start_date, end= end_date)
[*********************100%***********************]  1 of 1 completed
/tmp/ipykernel_3881/3973490860.py:2: FutureWarning: YF.download() has changed argument auto_adjust default to True
  yf.download(stock, start=start_date, end= end_date)
[*********************100%***********************]  1 of 1 completed
/tmp/ipykernel_3881/3973490860.py:2: FutureWarning: YF.download() has changed argument auto_adjust default to True
  yf.download(stock, start=start_date, end= end_date)
[*********************100%***********************]  1 of 1 completed
/tmp/ipykernel_3881/3973490860.py:2: FutureWarning: YF.download() has changed argument auto_adjust default to True
  yf.download(stock, start=start_date, end= end_date)
[*********************100%***********************]  1 of 1 completed
/tmp/ipykernel_3881/3973490860.py:2: FutureWarning: YF.download() has changed argument auto_adjust default to True
  yf.download(stock, start=start_date, end= end_date)
[*********************100%***********************]  1 of 1 completed

In [139]:
print(portfolio)

['RELIANCE.NS', 'TCS.NS', 'INFY.NS', 'HDFCBANK.NS', 'ICICIBANK.NS']

In [140]:
raw_data = {}

for stock in portfolio:
  raw_data[stock] = yf.download(stock, start=start_date, end= end_date)

/tmp/ipykernel_3881/2133735910.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  raw_data[stock] = yf.download(stock, start=start_date, end= end_date)
[*********************100%***********************]  1 of 1 completed
/tmp/ipykernel_3881/2133735910.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  raw_data[stock] = yf.download(stock, start=start_date, end= end_date)
[*********************100%***********************]  1 of 1 completed
/tmp/ipykernel_3881/2133735910.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  raw_data[stock] = yf.download(stock, start=start_date, end= end_date)
[*********************100%***********************]  1 of 1 completed
/tmp/ipykernel_3881/2133735910.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  raw_data[stock] = yf.download(stock, start=start_date, end= end_date)
[*********************100%***********************]  1 of 1 completed
/tmp/ipykernel_3881/2133735910.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  raw_data[stock] = yf.download(stock, start=start_date, end= end_date)
[*********************100%***********************]  1 of 1 completed

In [141]:
raw_data.keys()

dict_keys(['RELIANCE.NS', 'TCS.NS', 'INFY.NS', 'HDFCBANK.NS', 'ICICIBANK.NS'])

In [142]:
raw_data.values()

dict_values([Price             Close         High          Low         Open      Volume
Ticker      RELIANCE.NS  RELIANCE.NS  RELIANCE.NS  RELIANCE.NS RELIANCE.NS
Date
2023-01-02  1170.478027  1171.886668  1157.891242  1158.709143     5316175
2023-01-03  1161.912598  1169.160249  1157.709511  1165.547781     7658932
2023-01-04  1144.418213  1163.730055  1142.350684  1161.889687     9264891
2023-01-05  1142.373413  1152.529209  1137.806748  1146.667484    13637099
2023-01-06  1152.756348  1157.777455  1144.304622  1148.098818     6349597
...                 ...          ...          ...          ...         ...
2025-12-24  1551.028687  1568.448147  1546.449881  1565.461954     8815745
2025-12-26  1552.024048  1553.815812  1547.146696  1547.544758     2311495
2025-12-29  1538.486694  1550.929166  1536.495899  1547.743942     5972105
2025-12-30  1532.713379  1546.449794  1530.722584  1539.880194     8815884
2025-12-31  1563.172607  1569.742208  1533.907890  1533.907890     5771830

[740 rows x 5 columns], Price             Close         High          Low         Open   Volume
Ticker           TCS.NS       TCS.NS       TCS.NS       TCS.NS   TCS.NS
Date
2023-01-02  2877.781738  2882.546626  2854.619718  2877.384718   709547
2023-01-03  2921.811035  2929.443384  2863.530951  2869.442737  1245178
2023-01-04  2924.723145  2935.929322  2899.619971  2917.708405  1231668
2023-01-05  2921.590576  2944.708431  2895.869580  2938.443571  1826057
2023-01-06  2833.751465  2913.164094  2823.560134  2911.796389  2488376
...                 ...          ...          ...          ...      ...
2025-12-24  3198.595947  3206.402196  3176.526789  3184.236572  1367708
2025-12-26  3161.010986  3199.559901  3153.108506  3192.910307  1176664
2025-12-29  3133.544434  3168.720313  3125.256324  3161.010531  2079473
2025-12-30  3129.015137  3148.964151  3121.979913  3132.099003  2807593
2025-12-31  3089.887939  3128.244153  3082.467321  3122.461817  3362634

[740 rows x 5 columns], Price             Close         High          Low         Open   Volume
Ticker          INFY.NS      INFY.NS      INFY.NS      INFY.NS  INFY.NS
Date
2023-01-02  1368.097290  1370.341544  1350.188186  1359.120274  3801140
2023-01-03  1366.795776  1375.862542  1360.107833  1364.371916  4551130
2023-01-04  1341.884399  1365.404138  1338.562838  1365.404138  7059590
2023-01-05  1324.289551  1351.849060  1318.948269  1351.849060  9868404
2023-01-06  1300.320801  1324.109894  1298.525398  1319.621386  6443714
...                 ...          ...          ...          ...      ...
2025-12-24  1628.167480  1632.278472  1617.498330  1625.818291  4271167
2025-12-26  1621.022095  1633.453168  1616.715267  1628.167521  2006491
2025-12-29  1609.863525  1637.662008  1602.424525  1622.881866  4062817
2025-12-30  1587.252808  1612.995794  1582.554548  1612.114833  9395937
2025-12-31  1581.184204  1594.104567  1575.115455  1586.665566  6538656

[740 rows x 5 columns], Price            Close        High         Low        Open      Volume
Ticker     HDFCBANK.NS HDFCBANK.NS HDFCBANK.NS HDFCBANK.NS HDFCBANK.NS
Date
2023-01-02  770.927246  776.157665  766.122901  770.122593     4381378
2023-01-03  775.968262  777.695961  767.850486  767.850486     8378030
2023-01-04  762.099487  778.997667  760.655780  773.909272    10351600
2023-01-05  757.200439  765.886257  752.325082  764.442550    10941436
2023-01-06  754.691711  761.649772  747.023585  758.289076     9092462
...                ...         ...         ...         ...         ...
2025-12-24  980.975220  983.139437  976.843543  976.843543    13699996
2025-12-26  975.958191  980.975248  971.629816  979.794761     9360853
2025-12-29  975.564697  981.171968  971.137914  976.941883    13545749
2025-12-30  974.777771  978.811039  966.219311  974.089148    33155849
2025-12-31  975.072876  981.368710  971.531413  974.876118    10963454

[740 rows x 5 columns], Price             Close         High          Low         Open       Volume
Ticker     ICICIBANK.NS ICICIBANK.NS ICICIBANK.NS ICICIBANK.NS ICICIBANK.NS
Date
2023-01-02   873.285095   877.688039   865.108166   865.108166      4315403
2023-01-03   872.220703   876.672079   867.769387   869.462831      5846855
2023-01-04   870.043396   878.559050   865.882373   869.946651     12454582
2023-01-05   850.738159   873.817365   843.819205   871.785255     16547196
2023-01-06   841.980591   850.544617   832.690862   850.544617     14804613
...                 ...          ...          ...          ...          ...
2025-12-24  1348.432129  1356.761808  1346.250448  1352.398689      8955140
2025-12-26  1339.110596  1350.613595  1337.226456  1345.159575      2812144
2025-12-29  1332.070068  1344.366308  1330.285068  1340.796428      6057201
2025-12-30  1331.276611  1335.838131  1326.913371  1332.069972     18621277
2025-12-31  1331.673340  1338.713959  1328.301740  1331.574200      6150634

[740 rows x 5 columns]])

In [143]:
def standardize_data(df,ticker):
  df = df.reset_index()
  df.columns = [col[0] for col in df.columns]
  df["ticker"] = ticker
  return df

In [144]:
processed_data = {}
for stock in portfolio:
  processed_data[stock] = standardize_data(raw_data[stock], stock)

In [145]:
processed_data.values()

dict_values([          Date        Close         High          Low         Open    Volume  \
0   2023-01-02  1170.478027  1171.886668  1157.891242  1158.709143   5316175
1   2023-01-03  1161.912598  1169.160249  1157.709511  1165.547781   7658932
2   2023-01-04  1144.418213  1163.730055  1142.350684  1161.889687   9264891
3   2023-01-05  1142.373413  1152.529209  1137.806748  1146.667484  13637099
4   2023-01-06  1152.756348  1157.777455  1144.304622  1148.098818   6349597
..         ...          ...          ...          ...          ...       ...
735 2025-12-24  1551.028687  1568.448147  1546.449881  1565.461954   8815745
736 2025-12-26  1552.024048  1553.815812  1547.146696  1547.544758   2311495
737 2025-12-29  1538.486694  1550.929166  1536.495899  1547.743942   5972105
738 2025-12-30  1532.713379  1546.449794  1530.722584  1539.880194   8815884
739 2025-12-31  1563.172607  1569.742208  1533.907890  1533.907890   5771830

          ticker
0    RELIANCE.NS
1    RELIANCE.NS
2    RELIANCE.NS
3    RELIANCE.NS
4    RELIANCE.NS
..           ...
735  RELIANCE.NS
736  RELIANCE.NS
737  RELIANCE.NS
738  RELIANCE.NS
739  RELIANCE.NS

[740 rows x 7 columns],           Date        Close         High          Low         Open   Volume  \
0   2023-01-02  2877.781738  2882.546626  2854.619718  2877.384718   709547
1   2023-01-03  2921.811035  2929.443384  2863.530951  2869.442737  1245178
2   2023-01-04  2924.723145  2935.929322  2899.619971  2917.708405  1231668
3   2023-01-05  2921.590576  2944.708431  2895.869580  2938.443571  1826057
4   2023-01-06  2833.751465  2913.164094  2823.560134  2911.796389  2488376
..         ...          ...          ...          ...          ...      ...
735 2025-12-24  3198.595947  3206.402196  3176.526789  3184.236572  1367708
736 2025-12-26  3161.010986  3199.559901  3153.108506  3192.910307  1176664
737 2025-12-29  3133.544434  3168.720313  3125.256324  3161.010531  2079473
738 2025-12-30  3129.015137  3148.964151  3121.979913  3132.099003  2807593
739 2025-12-31  3089.887939  3128.244153  3082.467321  3122.461817  3362634

     ticker
0    TCS.NS
1    TCS.NS
2    TCS.NS
3    TCS.NS
4    TCS.NS
..      ...
735  TCS.NS
736  TCS.NS
737  TCS.NS
738  TCS.NS
739  TCS.NS

[740 rows x 7 columns],           Date        Close         High          Low         Open   Volume  \
0   2023-01-02  1368.097290  1370.341544  1350.188186  1359.120274  3801140
1   2023-01-03  1366.795776  1375.862542  1360.107833  1364.371916  4551130
2   2023-01-04  1341.884399  1365.404138  1338.562838  1365.404138  7059590
3   2023-01-05  1324.289551  1351.849060  1318.948269  1351.849060  9868404
4   2023-01-06  1300.320801  1324.109894  1298.525398  1319.621386  6443714
..         ...          ...          ...          ...          ...      ...
735 2025-12-24  1628.167480  1632.278472  1617.498330  1625.818291  4271167
736 2025-12-26  1621.022095  1633.453168  1616.715267  1628.167521  2006491
737 2025-12-29  1609.863525  1637.662008  1602.424525  1622.881866  4062817
738 2025-12-30  1587.252808  1612.995794  1582.554548  1612.114833  9395937
739 2025-12-31  1581.184204  1594.104567  1575.115455  1586.665566  6538656

      ticker
0    INFY.NS
1    INFY.NS
2    INFY.NS
3    INFY.NS
4    INFY.NS
..       ...
735  INFY.NS
736  INFY.NS
737  INFY.NS
738  INFY.NS
739  INFY.NS

[740 rows x 7 columns],           Date       Close        High         Low        Open    Volume  \
0   2023-01-02  770.927246  776.157665  766.122901  770.122593   4381378
1   2023-01-03  775.968262  777.695961  767.850486  767.850486   8378030
2   2023-01-04  762.099487  778.997667  760.655780  773.909272  10351600
3   2023-01-05  757.200439  765.886257  752.325082  764.442550  10941436
4   2023-01-06  754.691711  761.649772  747.023585  758.289076   9092462
..         ...         ...         ...         ...         ...       ...
735 2025-12-24  980.975220  983.139437  976.843543  976.843543  13699996
736 2025-12-26  975.958191  980.975248  971.629816  979.794761   9360853
737 2025-12-29  975.564697  981.171968  971.137914  976.941883  13545749
738 2025-12-30  974.777771  978.811039  966.219311  974.089148  33155849
739 2025-12-31  975.072876  981.368710  971.531413  974.876118  10963454

          ticker
0    HDFCBANK.NS
1    HDFCBANK.NS
2    HDFCBANK.NS
3    HDFCBANK.NS
4    HDFCBANK.NS
..           ...
735  HDFCBANK.NS
736  HDFCBANK.NS
737  HDFCBANK.NS
738  HDFCBANK.NS
739  HDFCBANK.NS

[740 rows x 7 columns],           Date        Close         High          Low         Open    Volume  \
0   2023-01-02   873.285095   877.688039   865.108166   865.108166   4315403
1   2023-01-03   872.220703   876.672079   867.769387   869.462831   5846855
2   2023-01-04   870.043396   878.559050   865.882373   869.946651  12454582
3   2023-01-05   850.738159   873.817365   843.819205   871.785255  16547196
4   2023-01-06   841.980591   850.544617   832.690862   850.544617  14804613
..         ...          ...          ...          ...          ...       ...
735 2025-12-24  1348.432129  1356.761808  1346.250448  1352.398689   8955140
736 2025-12-26  1339.110596  1350.613595  1337.226456  1345.159575   2812144
737 2025-12-29  1332.070068  1344.366308  1330.285068  1340.796428   6057201
738 2025-12-30  1331.276611  1335.838131  1326.913371  1332.069972  18621277
739 2025-12-31  1331.673340  1338.713959  1328.301740  1331.574200   6150634

           ticker
0    ICICIBANK.NS
1    ICICIBANK.NS
2    ICICIBANK.NS
3    ICICIBANK.NS
4    ICICIBANK.NS
..            ...
735  ICICIBANK.NS
736  ICICIBANK.NS
737  ICICIBANK.NS
738  ICICIBANK.NS
739  ICICIBANK.NS

[740 rows x 7 columns]])

In [146]:
processed_data.keys()

dict_keys(['RELIANCE.NS', 'TCS.NS', 'INFY.NS', 'HDFCBANK.NS', 'ICICIBANK.NS'])

In [147]:
processed_data.values()

dict_values([          Date        Close         High          Low         Open    Volume  \
0   2023-01-02  1170.478027  1171.886668  1157.891242  1158.709143   5316175
1   2023-01-03  1161.912598  1169.160249  1157.709511  1165.547781   7658932
2   2023-01-04  1144.418213  1163.730055  1142.350684  1161.889687   9264891
3   2023-01-05  1142.373413  1152.529209  1137.806748  1146.667484  13637099
4   2023-01-06  1152.756348  1157.777455  1144.304622  1148.098818   6349597
..         ...          ...          ...          ...          ...       ...
735 2025-12-24  1551.028687  1568.448147  1546.449881  1565.461954   8815745
736 2025-12-26  1552.024048  1553.815812  1547.146696  1547.544758   2311495
737 2025-12-29  1538.486694  1550.929166  1536.495899  1547.743942   5972105
738 2025-12-30  1532.713379  1546.449794  1530.722584  1539.880194   8815884
739 2025-12-31  1563.172607  1569.742208  1533.907890  1533.907890   5771830

          ticker
0    RELIANCE.NS
1    RELIANCE.NS
2    RELIANCE.NS
3    RELIANCE.NS
4    RELIANCE.NS
..           ...
735  RELIANCE.NS
736  RELIANCE.NS
737  RELIANCE.NS
738  RELIANCE.NS
739  RELIANCE.NS

[740 rows x 7 columns],           Date        Close         High          Low         Open   Volume  \
0   2023-01-02  2877.781738  2882.546626  2854.619718  2877.384718   709547
1   2023-01-03  2921.811035  2929.443384  2863.530951  2869.442737  1245178
2   2023-01-04  2924.723145  2935.929322  2899.619971  2917.708405  1231668
3   2023-01-05  2921.590576  2944.708431  2895.869580  2938.443571  1826057
4   2023-01-06  2833.751465  2913.164094  2823.560134  2911.796389  2488376
..         ...          ...          ...          ...          ...      ...
735 2025-12-24  3198.595947  3206.402196  3176.526789  3184.236572  1367708
736 2025-12-26  3161.010986  3199.559901  3153.108506  3192.910307  1176664
737 2025-12-29  3133.544434  3168.720313  3125.256324  3161.010531  2079473
738 2025-12-30  3129.015137  3148.964151  3121.979913  3132.099003  2807593
739 2025-12-31  3089.887939  3128.244153  3082.467321  3122.461817  3362634

     ticker
0    TCS.NS
1    TCS.NS
2    TCS.NS
3    TCS.NS
4    TCS.NS
..      ...
735  TCS.NS
736  TCS.NS
737  TCS.NS
738  TCS.NS
739  TCS.NS

[740 rows x 7 columns],           Date        Close         High          Low         Open   Volume  \
0   2023-01-02  1368.097290  1370.341544  1350.188186  1359.120274  3801140
1   2023-01-03  1366.795776  1375.862542  1360.107833  1364.371916  4551130
2   2023-01-04  1341.884399  1365.404138  1338.562838  1365.404138  7059590
3   2023-01-05  1324.289551  1351.849060  1318.948269  1351.849060  9868404
4   2023-01-06  1300.320801  1324.109894  1298.525398  1319.621386  6443714
..         ...          ...          ...          ...          ...      ...
735 2025-12-24  1628.167480  1632.278472  1617.498330  1625.818291  4271167
736 2025-12-26  1621.022095  1633.453168  1616.715267  1628.167521  2006491
737 2025-12-29  1609.863525  1637.662008  1602.424525  1622.881866  4062817
738 2025-12-30  1587.252808  1612.995794  1582.554548  1612.114833  9395937
739 2025-12-31  1581.184204  1594.104567  1575.115455  1586.665566  6538656

      ticker
0    INFY.NS
1    INFY.NS
2    INFY.NS
3    INFY.NS
4    INFY.NS
..       ...
735  INFY.NS
736  INFY.NS
737  INFY.NS
738  INFY.NS
739  INFY.NS

[740 rows x 7 columns],           Date       Close        High         Low        Open    Volume  \
0   2023-01-02  770.927246  776.157665  766.122901  770.122593   4381378
1   2023-01-03  775.968262  777.695961  767.850486  767.850486   8378030
2   2023-01-04  762.099487  778.997667  760.655780  773.909272  10351600
3   2023-01-05  757.200439  765.886257  752.325082  764.442550  10941436
4   2023-01-06  754.691711  761.649772  747.023585  758.289076   9092462
..         ...         ...         ...         ...         ...       ...
735 2025-12-24  980.975220  983.139437  976.843543  976.843543  13699996
736 2025-12-26  975.958191  980.975248  971.629816  979.794761   9360853
737 2025-12-29  975.564697  981.171968  971.137914  976.941883  13545749
738 2025-12-30  974.777771  978.811039  966.219311  974.089148  33155849
739 2025-12-31  975.072876  981.368710  971.531413  974.876118  10963454

          ticker
0    HDFCBANK.NS
1    HDFCBANK.NS
2    HDFCBANK.NS
3    HDFCBANK.NS
4    HDFCBANK.NS
..           ...
735  HDFCBANK.NS
736  HDFCBANK.NS
737  HDFCBANK.NS
738  HDFCBANK.NS
739  HDFCBANK.NS

[740 rows x 7 columns],           Date        Close         High          Low         Open    Volume  \
0   2023-01-02   873.285095   877.688039   865.108166   865.108166   4315403
1   2023-01-03   872.220703   876.672079   867.769387   869.462831   5846855
2   2023-01-04   870.043396   878.559050   865.882373   869.946651  12454582
3   2023-01-05   850.738159   873.817365   843.819205   871.785255  16547196
4   2023-01-06   841.980591   850.544617   832.690862   850.544617  14804613
..         ...          ...          ...          ...          ...       ...
735 2025-12-24  1348.432129  1356.761808  1346.250448  1352.398689   8955140
736 2025-12-26  1339.110596  1350.613595  1337.226456  1345.159575   2812144
737 2025-12-29  1332.070068  1344.366308  1330.285068  1340.796428   6057201
738 2025-12-30  1331.276611  1335.838131  1326.913371  1332.069972  18621277
739 2025-12-31  1331.673340  1338.713959  1328.301740  1331.574200   6150634

           ticker
0    ICICIBANK.NS
1    ICICIBANK.NS
2    ICICIBANK.NS
3    ICICIBANK.NS
4    ICICIBANK.NS
..            ...
735  ICICIBANK.NS
736  ICICIBANK.NS
737  ICICIBANK.NS
738  ICICIBANK.NS
739  ICICIBANK.NS

[740 rows x 7 columns]])

In [148]:
master_data = pd.concat(processed_data.values(), ignore_index = True)

In [149]:
master_data.head()

,Date,Close,High,Low,Open,Volume,ticker
0,2023-01-02,1170.478027,1171.886668,1157.891242,1158.709143,5316175,RELIANCE.NS
1,2023-01-03,1161.912598,1169.160249,1157.709511,1165.547781,7658932,RELIANCE.NS
2,2023-01-04,1144.418213,1163.730055,1142.350684,1161.889687,9264891,RELIANCE.NS
3,2023-01-05,1142.373413,1152.529209,1137.806748,1146.667484,13637099,RELIANCE.NS
4,2023-01-06,1152.756348,1157.777455,1144.304622,1148.098818,6349597,RELIANCE.NS

In [150]:
master_data.shape

(3700, 7)

In [151]:
master_data.isnull().sum()

Date      0
Close     0
High      0
Low       0
Open      0
Volume    0
ticker    0
dtype: int64

In [152]:
master_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3700 entries, 0 to 3699
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    3700 non-null   datetime64[ns]
 1   Close   3700 non-null   float64
 2   High    3700 non-null   float64
 3   Low     3700 non-null   float64
 4   Open    3700 non-null   float64
 5   Volume  3700 non-null   int64
 6   ticker  3700 non-null   object
dtypes: datetime64[ns](1), float64(4), int64(1), object(1)
memory usage: 202.5+ KB

In [153]:
master_data.head()

,Date,Close,High,Low,Open,Volume,ticker
0,2023-01-02,1170.478027,1171.886668,1157.891242,1158.709143,5316175,RELIANCE.NS
1,2023-01-03,1161.912598,1169.160249,1157.709511,1165.547781,7658932,RELIANCE.NS
2,2023-01-04,1144.418213,1163.730055,1142.350684,1161.889687,9264891,RELIANCE.NS
3,2023-01-05,1142.373413,1152.529209,1137.806748,1146.667484,13637099,RELIANCE.NS
4,2023-01-06,1152.756348,1157.777455,1144.304622,1148.098818,6349597,RELIANCE.NS

In [154]:
master_data = master_data.sort_values(by = ["ticker","Date"])

In [155]:
master_data.reset_index(drop = True)

,Date,Close,High,Low,Open,Volume,ticker
0,2023-01-02,770.927246,776.157665,766.122901,770.122593,4381378,HDFCBANK.NS
1,2023-01-03,775.968262,777.695961,767.850486,767.850486,8378030,HDFCBANK.NS
2,2023-01-04,762.099487,778.997667,760.655780,773.909272,10351600,HDFCBANK.NS
3,2023-01-05,757.200439,765.886257,752.325082,764.442550,10941436,HDFCBANK.NS
4,2023-01-06,754.691711,761.649772,747.023585,758.289076,9092462,HDFCBANK.NS
...,...,...,...,...,...,...,...
3695,2025-12-24,3198.595947,3206.402196,3176.526789,3184.236572,1367708,TCS.NS
3696,2025-12-26,3161.010986,3199.559901,3153.108506,3192.910307,1176664,TCS.NS
3697,2025-12-29,3133.544434,3168.720313,3125.256324,3161.010531,2079473,TCS.NS
3698,2025-12-30,3129.015137,3148.964151,3121.979913,3132.099003,2807593,TCS.NS
3699,2025-12-31,3089.887939,3128.244153,3082.467321,3122.461817,3362634,TCS.NS

In [156]:
master_data = master_data.reset_index(drop = True)

In [157]:
master_data.groupby("ticker")

In [158]:
master_data.groupby("ticker").groups.keys()

dict_keys(['HDFCBANK.NS', 'ICICIBANK.NS', 'INFY.NS', 'RELIANCE.NS', 'TCS.NS'])

In [159]:
master_data["Daily_Return"] = (master_data.groupby("ticker")["Close"].pct_change())

In [160]:
master_data.head(15)

,Date,Close,High,Low,Open,Volume,ticker,Daily_Return
0,2023-01-02,770.927246,776.157665,766.122901,770.122593,4381378,HDFCBANK.NS,NaN
1,2023-01-03,775.968262,777.695961,767.850486,767.850486,8378030,HDFCBANK.NS,0.006539
2,2023-01-04,762.099487,778.997667,760.655780,773.909272,10351600,HDFCBANK.NS,-0.017873
3,2023-01-05,757.200439,765.886257,752.325082,764.442550,10941436,HDFCBANK.NS,-0.006428
4,2023-01-06,754.691711,761.649772,747.023585,758.289076,9092462,HDFCBANK.NS,-0.003313
5,2023-01-09,756.159058,762.809494,752.609015,755.449049,10729340,HDFCBANK.NS,0.001944
6,2023-01-10,742.337585,757.342409,740.775544,757.342409,16371766,HDFCBANK.NS,-0.018279
7,2023-01-11,753.035034,756.395730,738.408847,742.171869,15195798,HDFCBANK.NS,0.014410
8,2023-01-12,757.058472,759.188497,749.840051,751.567750,9250070,HDFCBANK.NS,0.005343
9,2023-01-13,757.650085,762.028471,750.715658,756.750730,9244546,HDFCBANK.NS,0.000781
10,2023-01-16,750.384399,767.424605,748.017704,764.442546,14748094,HDFCBANK.NS,-0.009590
11,2023-01-17,761.555054,762.549054,746.692199,752.514291,10786354,HDFCBANK.NS,0.014887
12,2023-01-18,774.997925,777.033248,757.200333,759.709053,19090642,HDFCBANK.NS,0.017652
13,2023-01-19,778.216614,781.009325,772.962563,774.855919,11172162,HDFCBANK.NS,0.004153
14,2023-01-20,786.192383,790.002785,777.885318,778.216632,18843404,HDFCBANK.NS,0.010249

In [161]:
master_data["Cumulative_Return"] = ((1+master_data["Daily_Return"].groupby(master_data['ticker']).cumprod()))

In [162]:
master_data.head()

,Date,Close,High,Low,Open,Volume,ticker,Daily_Return,Cumulative_Return
0,2023-01-02,770.927246,776.157665,766.122901,770.122593,4381378,HDFCBANK.NS,NaN,NaN
1,2023-01-03,775.968262,777.695961,767.850486,767.850486,8378030,HDFCBANK.NS,0.006539,1.006539
2,2023-01-04,762.099487,778.997667,760.655780,773.909272,10351600,HDFCBANK.NS,-0.017873,0.999883
3,2023-01-05,757.200439,765.886257,752.325082,764.442550,10941436,HDFCBANK.NS,-0.006428,1.000001
4,2023-01-06,754.691711,761.649772,747.023585,758.289076,9092462,HDFCBANK.NS,-0.003313,1.000000

In [163]:
master_data.reset_index(drop= True)

,Date,Close,High,Low,Open,Volume,ticker,Daily_Return,Cumulative_Return
0,2023-01-02,770.927246,776.157665,766.122901,770.122593,4381378,HDFCBANK.NS,NaN,NaN
1,2023-01-03,775.968262,777.695961,767.850486,767.850486,8378030,HDFCBANK.NS,0.006539,1.006539
2,2023-01-04,762.099487,778.997667,760.655780,773.909272,10351600,HDFCBANK.NS,-0.017873,0.999883
3,2023-01-05,757.200439,765.886257,752.325082,764.442550,10941436,HDFCBANK.NS,-0.006428,1.000001
4,2023-01-06,754.691711,761.649772,747.023585,758.289076,9092462,HDFCBANK.NS,-0.003313,1.000000
...,...,...,...,...,...,...,...,...,...
3695,2025-12-24,3198.595947,3206.402196,3176.526789,3184.236572,1367708,TCS.NS,0.002719,1.000000
3696,2025-12-26,3161.010986,3199.559901,3153.108506,3192.910307,1176664,TCS.NS,-0.011750,1.000000
3697,2025-12-29,3133.544434,3168.720313,3125.256324,3161.010531,2079473,TCS.NS,-0.008689,1.000000
3698,2025-12-30,3129.015137,3148.964151,3121.979913,3132.099003,2807593,TCS.NS,-0.001445,1.000000
3699,2025-12-31,3089.887939,3128.244153,3082.467321,3122.461817,3362634,TCS.NS,-0.012505,1.000000

In [164]:
portfolio_metadata = pd.DataFrame({'ticker':['RELIANCE.NS','TCS.NS','INFY.NS','HDFCBANK.NS','ICICIBANK.NS'], 'weight':[0.3,0.25,0.2,0.15,0.1], 'Sector': ["Energy","Information Technology","Information Technology","Financial Services","Financial Services"]})

In [165]:
portfolio_metadata

         ticker  weight                  Sector
0   RELIANCE.NS    0.30                  Energy
1        TCS.NS    0.25  Information Technology
2       INFY.NS    0.20  Information Technology
3   HDFCBANK.NS    0.15      Financial Services
4  ICICIBANK.NS    0.10      Financial Services

In [166]:
portfolio_metadata.columns

Index(['ticker', 'weight', 'Sector'], dtype='object')

In [167]:
master_data = master_data.merge(portfolio_metadata, on = 'ticker', how = 'left')

In [168]:
master_data.head()

,Date,Close,High,Low,Open,Volume,ticker,Daily_Return,Cumulative_Return,weight,Sector
0,2023-01-02,770.927246,776.157665,766.122901,770.122593,4381378,HDFCBANK.NS,NaN,NaN,0.15,Financial Services
1,2023-01-03,775.968262,777.695961,767.850486,767.850486,8378030,HDFCBANK.NS,0.006539,1.006539,0.15,Financial Services
2,2023-01-04,762.099487,778.997667,760.655780,773.909272,10351600,HDFCBANK.NS,-0.017873,0.999883,0.15,Financial Services
3,2023-01-05,757.200439,765.886257,752.325082,764.442550,10941436,HDFCBANK.NS,-0.006428,1.000001,0.15,Financial Services
4,2023-01-06,754.691711,761.649772,747.023585,758.289076,9092462,HDFCBANK.NS,-0.003313,1.000000,0.15,Financial Services

In [169]:
master_data['Weighted_Return'] = (master_data['Daily_Return']*master_data['weight'])

In [170]:
master_data.head()

,Date,Close,High,Low,Open,Volume,ticker,Daily_Return,Cumulative_Return,weight,Sector,Weighted_Return
0,2023-01-02,770.927246,776.157665,766.122901,770.122593,4381378,HDFCBANK.NS,NaN,NaN,0.15,Financial Services,NaN
1,2023-01-03,775.968262,777.695961,767.850486,767.850486,8378030,HDFCBANK.NS,0.006539,1.006539,0.15,Financial Services,0.000981
2,2023-01-04,762.099487,778.997667,760.655780,773.909272,10351600,HDFCBANK.NS,-0.017873,0.999883,0.15,Financial Services,-0.002681
3,2023-01-05,757.200439,765.886257,752.325082,764.442550,10941436,HDFCBANK.NS,-0.006428,1.000001,0.15,Financial Services,-0.000964
4,2023-01-06,754.691711,761.649772,747.023585,758.289076,9092462,HDFCBANK.NS,-0.003313,1.000000,0.15,Financial Services,-0.000497

In [171]:
portfolio_returns = (master_data.groupby("Date")["Weighted_Return"].sum().reset_index())

In [172]:
portfolio_returns

          Date  Weighted_Return
0   2023-01-02         0.000000
1   2023-01-03         0.002298
2   2023-01-04        -0.010844
3   2023-01-05        -0.006609
4   2023-01-06        -0.009936
..         ...              ...
735 2025-12-24        -0.002440
736 2025-12-26        -0.005081
737 2025-12-29        -0.006752
738 2025-12-30        -0.004477
739 2025-12-31         0.002146

[740 rows x 2 columns]

In [173]:
portfolio_returns.columns = ["Date", "Portfolio_Daily_Return"]

In [174]:
portfolio_returns.head()

        Date  Portfolio_Daily_Return
0 2023-01-02                0.000000
1 2023-01-03                0.002298
2 2023-01-04               -0.010844
3 2023-01-05               -0.006609
4 2023-01-06               -0.009936

In [175]:
portfolio_returns["Portfolio_Cumulative_Return"] = ((1+portfolio_returns["Portfolio_Daily_Return"]).cumprod())

In [176]:
portfolio_returns.head()

        Date  Portfolio_Daily_Return  Portfolio_Cumulative_Return
0 2023-01-02                0.000000                     1.000000
1 2023-01-03                0.002298                     1.002298
2 2023-01-04               -0.010844                     0.991430
3 2023-01-05               -0.006609                     0.984877
4 2023-01-06               -0.009936                     0.975091

In [177]:
portfolio_returns['Portfolio_Cumulative_Percent'] = (portfolio_returns["Portfolio_Cumulative_Return"]-1)

In [178]:
portfolio_returns.head()

,Date,Portfolio_Daily_Return,Portfolio_Cumulative_Return,Portfolio_Cumulative_Percent
0,2023-01-02,0.000000,1.000000,0.000000
1,2023-01-03,0.002298,1.002298,0.002298
2,2023-01-04,-0.010844,0.991430,-0.008570
3,2023-01-05,-0.006609,0.984877,-0.015123
4,2023-01-06,-0.009936,0.975091,-0.024909

In [179]:
initial_investment= 50000000

In [180]:
portfolio_returns["Portfolio_Value"] = (initial_investment*portfolio_returns["Portfolio_Cumulative_Return"])

In [181]:
portfolio_returns.head()

,Date,Portfolio_Daily_Return,Portfolio_Cumulative_Return,Portfolio_Cumulative_Percent,Portfolio_Value
0,2023-01-02,0.000000,1.000000,0.000000,5.000000e+07
1,2023-01-03,0.002298,1.002298,0.002298,5.011491e+07
2,2023-01-04,-0.010844,0.991430,-0.008570,4.957149e+07
3,2023-01-05,-0.006609,0.984877,-0.015123,4.924385e+07
4,2023-01-06,-0.009936,0.975091,-0.024909,4.875457e+07

In [182]:
daily_variance = portfolio_returns["Portfolio_Daily_Return"].var()

In [183]:
daily_variance

7.867636111912504e-05

In [184]:
daily_volatility = portfolio_returns['Portfolio_Daily_Return'].std()

In [185]:
daily_volatility*100

0.8869969623348495

In [186]:
annual_volatility = daily_volatility*252**0.5

In [187]:
annual_volatility*100

14.080640256046422

In [188]:
risk_summary = pd.DataFrame({"Metric":["Daily_Variance","Daily_Volatility","Annualized_Volatility"], "Value": [daily_variance, daily_volatility, annual_volatility]})

In [189]:
risk_summary

                  Metric     Value
0         Daily_Variance  0.000079
1       Daily_Volatility  0.008870
2  Annualized_Volatility  0.140806

In [190]:
return_matrix = master_data.pivot(index = "Date", columns = "ticker", values = "Close")

In [191]:
return_matrix

ticker      HDFCBANK.NS  ICICIBANK.NS      INFY.NS  RELIANCE.NS       TCS.NS
Date
2023-01-02   770.927246    873.285095  1368.097290  1170.478027  2877.781738
2023-01-03   775.968262    872.220703  1366.795776  1161.912598  2921.811035
2023-01-04   762.099487    870.043396  1341.884399  1144.418213  2924.723145
2023-01-05   757.200439    850.738159  1324.289551  1142.373413  2921.590576
2023-01-06   754.691711    841.980591  1300.320801  1152.756348  2833.751465
...                 ...           ...          ...          ...          ...
2025-12-24   980.975220   1348.432129  1628.167480  1551.028687  3198.595947
2025-12-26   975.958191   1339.110596  1621.022095  1552.024048  3161.010986
2025-12-29   975.564697   1332.070068  1609.863525  1538.486694  3133.544434
2025-12-30   974.777771   1331.276611  1587.252808  1532.713379  3129.015137
2025-12-31   975.072876   1331.673340  1581.184204  1563.172607  3089.887939

[740 rows x 5 columns]

In [192]:
return_matrix = return_matrix.pct_change()

In [193]:
return_matrix

ticker      HDFCBANK.NS  ICICIBANK.NS   INFY.NS  RELIANCE.NS    TCS.NS
Date
2023-01-02          NaN           NaN       NaN          NaN       NaN
2023-01-03     0.006539     -0.001219 -0.000951    -0.007318  0.015300
2023-01-04    -0.017873     -0.002496 -0.018226    -0.015057  0.000997
2023-01-05    -0.006428     -0.022189 -0.013112    -0.001787 -0.001071
2023-01-06    -0.003313     -0.010294 -0.018099     0.009089 -0.030066
...                 ...           ...       ...          ...       ...
2025-12-24     0.000602     -0.002348 -0.002937    -0.007958  0.002719
2025-12-26    -0.005114     -0.006913 -0.004389     0.000642 -0.011750
2025-12-29    -0.000403     -0.005258 -0.006884    -0.008722 -0.008689
2025-12-30    -0.000807     -0.000596 -0.014045    -0.003753 -0.001445
2025-12-31     0.000303      0.000298 -0.003823     0.019873 -0.012505

[740 rows x 5 columns]

In [194]:
return_matrix = return_matrix.dropna(axis = 0)

In [195]:
return_matrix

ticker      HDFCBANK.NS  ICICIBANK.NS   INFY.NS  RELIANCE.NS    TCS.NS
Date
2023-01-03     0.006539     -0.001219 -0.000951    -0.007318  0.015300
2023-01-04    -0.017873     -0.002496 -0.018226    -0.015057  0.000997
2023-01-05    -0.006428     -0.022189 -0.013112    -0.001787 -0.001071
2023-01-06    -0.003313     -0.010294 -0.018099     0.009089 -0.030066
2023-01-09     0.001944      0.003735  0.024819     0.023612  0.033753
...                 ...           ...       ...          ...       ...
2025-12-24     0.000602     -0.002348 -0.002937    -0.007958  0.002719
2025-12-26    -0.005114     -0.006913 -0.004389     0.000642 -0.011750
2025-12-29    -0.000403     -0.005258 -0.006884    -0.008722 -0.008689
2025-12-30    -0.000807     -0.000596 -0.014045    -0.003753 -0.001445
2025-12-31     0.000303      0.000298 -0.003823     0.019873 -0.012505

[739 rows x 5 columns]

In [196]:
covariance_matrix = return_matrix.cov()

In [197]:
covariance_matrix

ticker        HDFCBANK.NS  ICICIBANK.NS   INFY.NS  RELIANCE.NS    TCS.NS
ticker
HDFCBANK.NS      0.000135      0.000060  0.000034     0.000053  0.000021
ICICIBANK.NS     0.000060      0.000124  0.000039     0.000053  0.000025
INFY.NS          0.000034      0.000039  0.000224     0.000048  0.000131
RELIANCE.NS      0.000053      0.000053  0.000048     0.000160  0.000043
TCS.NS           0.000021      0.000025  0.000131     0.000043  0.000155

In [198]:
correlation_matrix = return_matrix.corr()

In [199]:
correlation_matrix

ticker        HDFCBANK.NS  ICICIBANK.NS   INFY.NS  RELIANCE.NS    TCS.NS
ticker
HDFCBANK.NS      1.000000      0.460412  0.192730     0.362563  0.143191
ICICIBANK.NS     0.460412      1.000000  0.233036     0.379771  0.184043
INFY.NS          0.192730      0.233036  1.000000     0.251968  0.702551
RELIANCE.NS      0.362563      0.379771  0.251968     1.000000  0.275337
TCS.NS           0.143191      0.184043  0.702551     0.275337  1.000000

In [200]:
portfolio_metadata

         ticker  weight                  Sector
0   RELIANCE.NS    0.30                  Energy
1        TCS.NS    0.25  Information Technology
2       INFY.NS    0.20  Information Technology
3   HDFCBANK.NS    0.15      Financial Services
4  ICICIBANK.NS    0.10      Financial Services

In [201]:
covariance_matrix

ticker        HDFCBANK.NS  ICICIBANK.NS   INFY.NS  RELIANCE.NS    TCS.NS
ticker
HDFCBANK.NS      0.000135      0.000060  0.000034     0.000053  0.000021
ICICIBANK.NS     0.000060      0.000124  0.000039     0.000053  0.000025
INFY.NS          0.000034      0.000039  0.000224     0.000048  0.000131
RELIANCE.NS      0.000053      0.000053  0.000048     0.000160  0.000043
TCS.NS           0.000021      0.000025  0.000131     0.000043  0.000155

In [202]:
weights = portfolio_metadata.set_index("ticker")["weight"]

In [203]:
weights

ticker
RELIANCE.NS     0.30
TCS.NS          0.25
INFY.NS         0.20
HDFCBANK.NS     0.15
ICICIBANK.NS    0.10
Name: weight, dtype: float64

In [204]:
weights = weights.reindex(covariance_matrix.columns)

In [205]:
weights

ticker
HDFCBANK.NS     0.15
ICICIBANK.NS    0.10
INFY.NS         0.20
RELIANCE.NS     0.30
TCS.NS          0.25
Name: weight, dtype: float64

In [206]:
weights.values

array([0.15, 0.1 , 0.2 , 0.3 , 0.25])

In [207]:
portfolio_variance =(weights.values.T @covariance_matrix.values @weights.values)

In [208]:
portfolio_variance

np.float64(7.878278599310196e-05)

In [209]:
portfolio_volatility = np.sqrt(portfolio_variance)

In [210]:
portfolio_volatility*100

np.float64(0.8875966763857444)

In [211]:
portfolio_annual_volatility = portfolio_volatility*np.sqrt(252)

In [212]:
portfolio_annual_volatility*100

np.float64(14.090160421464937)

In [213]:
expected_daily_return = return_matrix.mean()

In [214]:
expected_daily_return

ticker
HDFCBANK.NS     0.000386
ICICIBANK.NS    0.000633
INFY.NS         0.000308
RELIANCE.NS     0.000471
TCS.NS          0.000173
dtype: float64

In [215]:
expected_annual_return = expected_daily_return*252

In [216]:
expected_annual_return

ticker
HDFCBANK.NS     0.097274
ICICIBANK.NS    0.159480
INFY.NS         0.077573
RELIANCE.NS     0.118729
TCS.NS          0.043655
dtype: float64

In [217]:
expected_annual_return = expected_annual_return.reindex(weights.index)

In [218]:
expected_annual_return

ticker
HDFCBANK.NS     0.097274
ICICIBANK.NS    0.159480
INFY.NS         0.077573
RELIANCE.NS     0.118729
TCS.NS          0.043655
dtype: float64

In [219]:
individual_expected_return = (weights*expected_annual_return)

In [220]:
portfolio_expected_return = individual_expected_return.sum()

In [221]:
portfolio_expected_return

np.float64(0.09258609578601194)

In [222]:
portfolio_expected_return*100

np.float64(9.258609578601193)

In [223]:
risk_free_rate = 0.067

In [224]:
sharpe_ratio = (portfolio_expected_return - risk_free_rate)/portfolio_annual_volatility

In [225]:
sharpe_ratio

np.float64(0.18158839232968638)

In [226]:
benchmark_data = yf.download("^NSEI", start = start_date, end = end_date, auto_adjust = True)

[*********************100%***********************]  1 of 1 completed

In [227]:
benchmark_data['Benchmark_Return'] = benchmark_data['Close'].fillna(0).pct_change()

In [228]:
benchmark_data.dropna()

Price,Close,High,Low,Open,Volume,Benchmark_Return
Ticker,^NSEI,^NSEI,^NSEI,^NSEI,^NSEI,
Date,,,,,,
2023-01-03,18232.550781,18251.949219,18149.800781,18163.199219,208700,0.001929
2023-01-04,18042.949219,18243.000000,18020.599609,18230.650391,235200,-0.010399
2023-01-05,17992.150391,18120.300781,17892.599609,18101.949219,269900,-0.002815
2023-01-06,17859.449219,18047.400391,17795.550781,18008.050781,238200,-0.007376
2023-01-09,18101.199219,18141.400391,17936.150391,17952.550781,257200,0.013536
...,...,...,...,...,...,...
2025-12-24,26142.099609,26236.400391,26123.000000,26170.650391,188800,-0.001339
2025-12-26,26042.300781,26144.199219,26008.599609,26121.250000,142200,-0.003818
2025-12-29,25942.099609,26106.800781,25920.300781,26063.349609,234300,-0.003848
2025-12-30,25938.849609,25976.750000,25878.000000,25940.900391,396900,-0.000125
2025-12-31,26129.599609,26187.949219,25969.000000,25971.050781,246300,0.007354

In [229]:
benchmark_data["Benchmark_Cumulative_Return"] = ((1+benchmark_data["Benchmark_Return"].fillna(0)).cumprod())

In [230]:
portfolio_returns

,Date,Portfolio_Daily_Return,Portfolio_Cumulative_Return,Portfolio_Cumulative_Percent,Portfolio_Value
0,2023-01-02,0.000000,1.000000,0.000000,5.000000e+07
1,2023-01-03,0.002298,1.002298,0.002298,5.011491e+07
2,2023-01-04,-0.010844,0.991430,-0.008570,4.957149e+07
3,2023-01-05,-0.006609,0.984877,-0.015123,4.924385e+07
4,2023-01-06,-0.009936,0.975091,-0.024909,4.875457e+07
...,...,...,...,...,...
735,2025-12-24,-0.002440,1.292598,0.292598,6.462988e+07
736,2025-12-26,-0.005081,1.286030,0.286030,6.430148e+07
737,2025-12-29,-0.006752,1.277346,0.277346,6.386732e+07
738,2025-12-30,-0.004477,1.271628,0.271628,6.358140e+07
739,2025-12-31,0.002146,1.274357,0.274357,6.371786e+07

In [231]:
benchmark_data.reset_index()

Price,Date,Close,High,Low,Open,Volume,Benchmark_Return,Benchmark_Cumulative_Return
Ticker,,^NSEI,^NSEI,^NSEI,^NSEI,^NSEI,,
0,2023-01-02,18197.449219,18215.150391,18086.500000,18131.699219,256100,NaN,1.000000
1,2023-01-03,18232.550781,18251.949219,18149.800781,18163.199219,208700,0.001929,1.001929
2,2023-01-04,18042.949219,18243.000000,18020.599609,18230.650391,235200,-0.010399,0.991510
3,2023-01-05,17992.150391,18120.300781,17892.599609,18101.949219,269900,-0.002815,0.988718
4,2023-01-06,17859.449219,18047.400391,17795.550781,18008.050781,238200,-0.007376,0.981426
...,...,...,...,...,...,...,...,...
735,2025-12-24,26142.099609,26236.400391,26123.000000,26170.650391,188800,-0.001339,1.436580
736,2025-12-26,26042.300781,26144.199219,26008.599609,26121.250000,142200,-0.003818,1.431096
737,2025-12-29,25942.099609,26106.800781,25920.300781,26063.349609,234300,-0.003848,1.425590
738,2025-12-30,25938.849609,25976.750000,25878.000000,25940.900391,396900,-0.000125,1.425411
739,2025-12-31,26129.599609,26187.949219,25969.000000,25971.050781,246300,0.007354,1.435894

In [232]:
benchmark_data = benchmark_data.reset_index()

In [233]:
benchmark_data

Price,Date,Close,High,Low,Open,Volume,Benchmark_Return,Benchmark_Cumulative_Return
Ticker,,^NSEI,^NSEI,^NSEI,^NSEI,^NSEI,,
0,2023-01-02,18197.449219,18215.150391,18086.500000,18131.699219,256100,NaN,1.000000
1,2023-01-03,18232.550781,18251.949219,18149.800781,18163.199219,208700,0.001929,1.001929
2,2023-01-04,18042.949219,18243.000000,18020.599609,18230.650391,235200,-0.010399,0.991510
3,2023-01-05,17992.150391,18120.300781,17892.599609,18101.949219,269900,-0.002815,0.988718
4,2023-01-06,17859.449219,18047.400391,17795.550781,18008.050781,238200,-0.007376,0.981426
...,...,...,...,...,...,...,...,...
735,2025-12-24,26142.099609,26236.400391,26123.000000,26170.650391,188800,-0.001339,1.436580
736,2025-12-26,26042.300781,26144.199219,26008.599609,26121.250000,142200,-0.003818,1.431096
737,2025-12-29,25942.099609,26106.800781,25920.300781,26063.349609,234300,-0.003848,1.425590
738,2025-12-30,25938.849609,25976.750000,25878.000000,25940.900391,396900,-0.000125,1.425411
739,2025-12-31,26129.599609,26187.949219,25969.000000,25971.050781,246300,0.007354,1.435894

In [234]:
#Now compare the Portfolio Cumulative return and benchmark cumulative return

In [235]:
benchmark_return = benchmark_data[["Date","Benchmark_Return", "Benchmark_Cumulative_Return"]]

In [236]:
benchmark_return

Price        Date Benchmark_Return Benchmark_Cumulative_Return
Ticker
0      2023-01-02              NaN                    1.000000
1      2023-01-03         0.001929                    1.001929
2      2023-01-04        -0.010399                    0.991510
3      2023-01-05        -0.002815                    0.988718
4      2023-01-06        -0.007376                    0.981426
..            ...              ...                         ...
735    2025-12-24        -0.001339                    1.436580
736    2025-12-26        -0.003818                    1.431096
737    2025-12-29        -0.003848                    1.425590
738    2025-12-30        -0.000125                    1.425411
739    2025-12-31         0.007354                    1.435894

[740 rows x 3 columns]

In [237]:
benchmark_return.columns = ["Date","Benchmark_Return","Benchmark_Cumulative_Return"]

In [238]:
portfolio_comparison = portfolio_returns[["Date","Portfolio_Cumulative_Return"]].merge(benchmark_return, on = "Date", how = "inner")

In [239]:
portfolio_comparison

,Date,Portfolio_Cumulative_Return,Benchmark_Return,Benchmark_Cumulative_Return
0,2023-01-02,1.000000,NaN,1.000000
1,2023-01-03,1.002298,0.001929,1.001929
2,2023-01-04,0.991430,-0.010399,0.991510
3,2023-01-05,0.984877,-0.002815,0.988718
4,2023-01-06,0.975091,-0.007376,0.981426
...,...,...,...,...
735,2025-12-24,1.292598,-0.001339,1.436580
736,2025-12-26,1.286030,-0.003818,1.431096
737,2025-12-29,1.277346,-0.003848,1.425590
738,2025-12-30,1.271628,-0.000125,1.425411
739,2025-12-31,1.274357,0.007354,1.435894

In [240]:
portfolio_comparison = portfolio_returns[["Date","Portfolio_Daily_Return","Portfolio_Cumulative_Return"]].merge(benchmark_return,on = "Date", how = "inner")

In [241]:
portfolio_comparison.dropna()

,Date,Portfolio_Daily_Return,Portfolio_Cumulative_Return,Benchmark_Return,Benchmark_Cumulative_Return
1,2023-01-03,0.002298,1.002298,0.001929,1.001929
2,2023-01-04,-0.010844,0.991430,-0.010399,0.991510
3,2023-01-05,-0.006609,0.984877,-0.002815,0.988718
4,2023-01-06,-0.009936,0.975091,-0.007376,0.981426
5,2023-01-09,0.021151,0.995715,0.013536,0.994711
...,...,...,...,...,...
735,2025-12-24,-0.002440,1.292598,-0.001339,1.436580
736,2025-12-26,-0.005081,1.286030,-0.003818,1.431096
737,2025-12-29,-0.006752,1.277346,-0.003848,1.425590
738,2025-12-30,-0.004477,1.271628,-0.000125,1.425411
739,2025-12-31,0.002146,1.274357,0.007354,1.435894

In [242]:
beta = portfolio_comparison["Portfolio_Daily_Return"].cov(portfolio_comparison["Benchmark_Return"]/portfolio_comparison["Benchmark_Return"].var())

In [243]:
beta

np.float64(1.0013108380724793)

In [244]:
years = (benchmark_return["Date"].iloc[-1] - benchmark_return["Date"].iloc[0]).days/365.25

In [245]:
years

2.9952087611225187

In [246]:
#benchmark CAGR
benchmark_cagr = (benchmark_return['Benchmark_Cumulative_Return'].iloc[-1]/benchmark_return['Benchmark_Cumulative_Return'].iloc[0])**(1/years)-1

In [247]:
benchmark_cagr*100

np.float64(12.838644120771736)

In [248]:
portfolio_cagr = (portfolio_returns["Portfolio_Cumulative_Return"].iloc[-1]/portfolio_returns["Portfolio_Cumulative_Return"].iloc[0])**(1/years)-1

In [249]:
portfolio_cagr*100

np.float64(8.43093566538231)

In [250]:
required_return = risk_free_rate+beta*(benchmark_cagr-risk_free_rate)

In [251]:
alpha = portfolio_cagr - required_return
alpha

np.float64(-0.04415755223816334)

In [252]:
alpha*100

np.float64(-4.415755223816334)

In [253]:
treynor_ratio = (portfolio_cagr - risk_free_rate)/ beta

In [254]:
treynor_ratio*100

np.float64(1.7286696593780577)

In [255]:
benchmark_treynor = (benchmark_cagr - risk_free_rate)

In [256]:
benchmark_treynor *100

np.float64(6.138644120771736)

In [257]:
performance_summary = {"Cumulative Summary": portfolio_returns["Portfolio_Cumulative_Return"].iloc[-1]-1,'CAGR': portfolio_cagr, "Annualized_Volatility": portfolio_annual_volatility, "Sharpe Ratio": sharpe_ratio, "Beta": beta,"Jensen Alpha":alpha, "Treynor Ratio": treynor_ratio}

In [258]:
performance_summary_df = pd.DataFrame(performance_summary.items(), columns = ["Metric","Portfolio"])

In [259]:
performance_summary_df

                  Metric  Portfolio
0     Cumulative Summary   0.274357
1                   CAGR   0.084309
2  Annualized_Volatility   0.140902
3           Sharpe Ratio   0.181588
4                   Beta   1.001311
5           Jensen Alpha  -0.044158
6          Treynor Ratio   0.017287

In [260]:
benchmark_metrics = {"Cumulative Summary": benchmark_return["Benchmark_Cumulative_Return"].iloc[-1]-1,"CAGR": benchmark_cagr, "Beta": 1, "Alpha": 0, "Treynor Ratio": benchmark_treynor}

In [261]:
benchmark_summary_df = pd.DataFrame(benchmark_metrics.items(), columns = ["Metric","Benchmark"])

In [262]:
performance_summary_df= performance_summary_df.merge(benchmark_summary_df, on = "Metric", how = "left")

In [263]:
performance_summary_df

                  Metric  Portfolio  Benchmark
0     Cumulative Summary   0.274357   0.435894
1                   CAGR   0.084309   0.128386
2  Annualized_Volatility   0.140902        NaN
3           Sharpe Ratio   0.181588        NaN
4                   Beta   1.001311   1.000000
5           Jensen Alpha  -0.044158        NaN
6          Treynor Ratio   0.017287   0.061386

In [264]:
performance_summary_df.to_csv("performance_summary.csv", index=False)

In [266]:


master_data.to_csv("master_data.csv", index=False)

portfolio_returns.to_csv("portfolio_returns.csv", index=False)

benchmark_return.to_csv("benchmark_return.csv", index=False)

portfolio_comparison.to_csv("portfolio_comparison.csv", index=False)

performance_summary_df.to_csv("performance_summary.csv", index=False)

correlation_matrix.to_csv("correlation_matrix.csv", index=True)

covariance_matrix.to_csv("covariance_matrix.csv", index=True)

print("All 7 CSV files created successfully.")

All 7 CSV files created successfully.

In [267]:
import zipfile
from google.colab import files

files_to_zip = [
    "master_data.csv",
    "portfolio_returns.csv",
    "benchmark_return.csv",
    "portfolio_comparison.csv",
    "performance_summary.csv",
    "correlation_matrix.csv",
    "covariance_matrix.csv"
]

with zipfile.ZipFile("portfolio_powerbi_data.zip", "w") as zipf:
    for file in files_to_zip:
        zipf.write(file)

files.download("portfolio_powerbi_data.zip")